// packages/solid/src/components/file-upload/file-upload-hidden-input.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useFieldContext } from '../field/index.tsx'
import { useFileUploadContext } from './use-file-upload-context.ts'

export interface FileUploadHiddenInputBaseProps extends PolymorphicProps<'input'> {}
export interface FileUploadHiddenInputProps extends HTMLProps<'input'>, FileUploadHiddenInputBaseProps {}

export const FileUploadHiddenInput = (props: FileUploadHiddenInputProps) => {
  const fileUpload = useFileUploadContext()
  const mergedProps = mergeProps(() => fileUpload().getHiddenInputProps(), props)
  const field = useFieldContext()

  return <codesign.input aria-describedby={field?.().ariaDescribedby} {...mergedProps} />
}

// packages/vue/src/components/file-upload/file-upload-hidden-input.vue
<script lang="ts">
import type { InputHTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface FileUploadHiddenInputBaseProps extends PolymorphicProps {}
export interface FileUploadHiddenInputProps
  extends
    FileUploadHiddenInputBaseProps,
    /**
     * @vue-ignore
     */
    InputHTMLAttributes {}
</script>

<script setup lang="ts">
import { codesign } from '../factory.ts'
import { useFileUploadContext } from './use-file-upload-context.ts'
import { useFieldContext } from '../field/index.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

defineProps<FileUploadHiddenInputProps>()
const fileUpload = useFileUploadContext()
const field = useFieldContext()

useForwardExpose()
</script>

<template>
  <codesign.input
    :aria-describedby="field?.ariaDescribedby"
    v-bind="fileUpload.getHiddenInputProps()"
    :as-child="asChild"
  >
    <slot />
  </codesign.input>
</template>
