// packages/svelte/src/lib/components/qr-code/examples/overlay.svelte
<script lang="ts">
  import { QrCode } from '@codesign-ui/svelte/qr-code'
  import styles from 'styles/qr-code.module.css'
</script>

<QrCode.Root class={styles.Root} defaultValue="http://codesign.chat" encoding={{ ecc: 'H' }}>
  <QrCode.Frame class={styles.Frame}>
    <QrCode.Pattern class={styles.Pattern} />
  </QrCode.Frame>
  <QrCode.Overlay class={styles.Overlay}>
    <img src="https://codesign.chat/icon-192.png" alt="Codesign UI Logo" />
  </QrCode.Overlay>
</QrCode.Root>

// packages/react/src/components/qr-code/examples/overlay.tsx
import { QrCode } from '@codesign-ui/react/qr-code'
import styles from 'styles/qr-code.module.css'

export const Overlay = () => {
  return (
    <QrCode.Root className={styles.Root} defaultValue="http://codesign.chat" encoding={{ ecc: 'H' }}>
      <QrCode.Frame className={styles.Frame}>
        <QrCode.Pattern className={styles.Pattern} />
      </QrCode.Frame>
      <QrCode.Overlay className={styles.Overlay}>
        <img src="https://codesign.chat/icon-192.png" alt="Codesign UI Logo" />
      </QrCode.Overlay>
    </QrCode.Root>
  )
}
