// packages/solid/src/ai/terminal/terminal.tsx
import { For, Show, createContext, createSignal, onMount, splitProps, useContext } from 'solid-js'
import type { JSX } from 'solid-js'
import { parseAnsi } from './ansi.ts'

const SCOPE = 'terminal'

interface TerminalContextValue {
  autoScroll: boolean
  isStreaming: boolean
  onClear?: () => void
  output: string
}

const TerminalContext = createContext<TerminalContextValue>()

export function useTerminal(): TerminalContextValue {
  const context = useContext(TerminalContext)
  if (!context) {
    throw new Error('Terminal parts must be used within Terminal')
  }
  return context
}

export type TerminalProps = JSX.HTMLAttributes<HTMLDivElement> & {
  autoScroll?: boolean
  isStreaming?: boolean
  onClear?: () => void
  output: string
}

export function Terminal(props: TerminalProps) {
  const [local, rest] = splitProps(props, ['autoScroll', 'isStreaming', 'onClear', 'output', 'children'])

  return (
    <TerminalContext.Provider
      value={{
        autoScroll: local.autoScroll ?? true,
        isStreaming: local.isStreaming ?? false,
        onClear: local.onClear,
        output: local.output,
      }}
    >
      <div data-scope={SCOPE} data-part="root" {...rest}>
        {local.children ?? (
          <>
            <TerminalHeader>
              <TerminalTitle />
              <div data-scope={SCOPE} data-part="header-actions">
                <TerminalStatus />
                <TerminalActions>
                  <TerminalCopyButton />
                  <Show when={local.onClear}>
                    <TerminalClearButton />
                  </Show>
                </TerminalActions>
              </div>
            </TerminalHeader>
            <TerminalContent />
          </>
        )}
      </div>
    </TerminalContext.Provider>
  )
}

export type TerminalHeaderProps = JSX.HTMLAttributes<HTMLDivElement>

export function TerminalHeader(props: TerminalHeaderProps) {
  return <div data-scope={SCOPE} data-part="header" {...props} />
}

export type TerminalTitleProps = JSX.HTMLAttributes<HTMLDivElement>

export function TerminalTitle(props: TerminalTitleProps) {
  const [local, rest] = splitProps(props, ['children'])
  return (
    <div data-scope={SCOPE} data-part="title" {...rest}>
      {local.children ?? 'Terminal'}
    </div>
  )
}

export type TerminalStatusProps = JSX.HTMLAttributes<HTMLDivElement>

export function TerminalStatus(props: TerminalStatusProps) {
  const [local, rest] = splitProps(props, ['children'])
  const { isStreaming } = useTerminal()
  return (
    <Show when={isStreaming}>
      <div data-scope={SCOPE} data-part="status" {...rest}>
        {local.children}
      </div>
    </Show>
  )
}

export type TerminalActionsProps = JSX.HTMLAttributes<HTMLDivElement>

export function TerminalActions(props: TerminalActionsProps) {
  return <div data-scope={SCOPE} data-part="actions" {...props} />
}

export type TerminalCopyButtonProps = JSX.HTMLAttributes<HTMLButtonElement> & {
  timeout?: number
}

export function TerminalCopyButton(props: TerminalCopyButtonProps) {
  const [local, rest] = splitProps(props, ['timeout', 'children', 'onClick'])
  const { output } = useTerminal()
  const [isCopied, setIsCopied] = createSignal(false)
  let timer: ReturnType<typeof setTimeout> | undefined

  return (
    <button
      aria-label="Copy"
      data-copied={isCopied() || undefined}
      data-scope={SCOPE}
      data-part="copy-button"
      onClick={(event) => {
        ;(local.onClick as any)?.(event)
        navigator.clipboard
          .writeText(output)
          .then(() => {
            setIsCopied(true)
            if (timer) clearTimeout(timer)
            timer = setTimeout(() => setIsCopied(false), local.timeout ?? 2000)
          })
          .catch(() => {
            // clipboard unavailable
          })
      }}
      type="button"
      {...rest}
    >
      <Show when={typeof local.children === 'function'} fallback={local.children}>
        {(local.children as unknown as (isCopied: boolean) => JSX.Element)(isCopied())}
      </Show>
    </button>
  )
}

export type TerminalClearButtonProps = JSX.HTMLAttributes<HTMLButtonElement>

export function TerminalClearButton(props: TerminalClearButtonProps) {
  const [local, rest] = splitProps(props, ['onClick', 'children'])
  const { onClear } = useTerminal()

  if (!onClear) {
    return null
  }

  return (
    <button
      aria-label="Clear"
      data-scope={SCOPE}
      data-part="clear-button"
      onClick={(event) => {
        onClear?.()
        ;(local.onClick as any)?.(event)
      }}
      type="button"
      {...rest}
    />
  )
}

export type TerminalContentProps = JSX.HTMLAttributes<HTMLDivElement>

export function TerminalContent(props: TerminalContentProps) {
  const [local, rest] = splitProps(props, ['children'])
  const { output, isStreaming, autoScroll } = useTerminal()
  let containerRef: HTMLDivElement | undefined

  onMount(() => {
    if (autoScroll && containerRef) {
      containerRef.scrollTop = containerRef.scrollHeight
    }
  })

  return (
    <div data-scope={SCOPE} data-part="content" ref={containerRef} {...rest}>
      {local.children ?? (
        <pre data-scope={SCOPE} data-part="output">
          <For each={parseAnsi(output)}>
            {(segment) => (
              <span
                style={{
                  color: segment.color,
                  'font-weight': segment.bold ? 'bold' : undefined,
                  opacity: segment.faint ? 0.6 : undefined,
                }}
              >
                {segment.text}
              </span>
            )}
          </For>
          <Show when={isStreaming}>
            <span data-scope={SCOPE} data-part="cursor" />
          </Show>
        </pre>
      )}
    </div>
  )
}

// packages/react/src/ai/terminal/terminal.tsx
import AnsiModule from 'ansi-to-react'
import { resolveInterop } from '../interop.ts'

const Ansi = resolveInterop<React.ComponentType<{ children: string }>>(AnsiModule)
import type { ComponentProps, HTMLAttributes, ReactNode } from 'react'
import { createContext, useCallback, useContext, useEffect, useMemo, useRef } from 'react'
import { useCopyToClipboard } from '../use-copy.ts'

interface TerminalContextType {
  output: string
  isStreaming: boolean
  autoScroll: boolean
  onClear?: () => void
}

const TerminalContext = createContext<TerminalContextType>({
  autoScroll: true,
  isStreaming: false,
  output: '',
})

export function useTerminal() {
  return useContext(TerminalContext)
}

export type TerminalProps = HTMLAttributes<HTMLDivElement> & {
  output: string
  isStreaming?: boolean
  autoScroll?: boolean
  onClear?: () => void
}

export function Terminal({
  output,
  isStreaming = false,
  autoScroll = true,
  onClear,
  children,
  ...props
}: TerminalProps) {
  const contextValue = useMemo(
    () => ({ autoScroll, isStreaming, onClear, output }),
    [autoScroll, isStreaming, onClear, output],
  )

  return (
    <TerminalContext.Provider value={contextValue}>
      <div data-scope="terminal" data-part="root" {...props}>
        {children ?? (
          <>
            <TerminalHeader>
              <TerminalTitle />
              <div data-scope="terminal" data-part="header-actions">
                <TerminalStatus />
                <TerminalActions>
                  <TerminalCopyButton />
                  {onClear && <TerminalClearButton />}
                </TerminalActions>
              </div>
            </TerminalHeader>
            <TerminalContent />
          </>
        )}
      </div>
    </TerminalContext.Provider>
  )
}

export type TerminalHeaderProps = HTMLAttributes<HTMLDivElement>

export function TerminalHeader(props: TerminalHeaderProps) {
  return <div data-scope="terminal" data-part="header" {...props} />
}

export type TerminalTitleProps = HTMLAttributes<HTMLDivElement>

export function TerminalTitle({ children, ...props }: TerminalTitleProps) {
  return (
    <div data-scope="terminal" data-part="title" {...props}>
      {children ?? 'Terminal'}
    </div>
  )
}

export type TerminalStatusProps = HTMLAttributes<HTMLDivElement>

export function TerminalStatus({ children, ...props }: TerminalStatusProps) {
  const { isStreaming } = useTerminal()

  if (!isStreaming) {
    return null
  }

  return (
    <div data-scope="terminal" data-part="status" {...props}>
      {children}
    </div>
  )
}

export type TerminalActionsProps = HTMLAttributes<HTMLDivElement>

export function TerminalActions(props: TerminalActionsProps) {
  return <div data-scope="terminal" data-part="actions" {...props} />
}

export type TerminalCopyButtonProps = Omit<ComponentProps<'button'>, 'children'> & {
  onCopy?: () => void
  onError?: (error: Error) => void
  timeout?: number
  children?: ReactNode | ((isCopied: boolean) => ReactNode)
}

export function TerminalCopyButton({ onCopy, onError, timeout, children, ...props }: TerminalCopyButtonProps) {
  const { output } = useTerminal()
  const { copy, isCopied } = useCopyToClipboard({ onCopy, onError, timeout })

  return (
    <button
      type="button"
      aria-label="Copy"
      data-scope="terminal"
      data-part="copy-button"
      data-copied={isCopied || undefined}
      onClick={() => copy(output)}
      {...props}
    >
      {typeof children === 'function' ? children(isCopied) : children}
    </button>
  )
}

export type TerminalClearButtonProps = ComponentProps<'button'>

export function TerminalClearButton({ onClick, ...props }: TerminalClearButtonProps) {
  const { onClear } = useTerminal()

  const handleClick = useCallback(
    (e: React.MouseEvent<HTMLButtonElement>) => {
      onClear?.()
      onClick?.(e)
    },
    [onClear, onClick],
  )

  if (!onClear) {
    return null
  }

  return (
    <button
      type="button"
      aria-label="Clear"
      data-scope="terminal"
      data-part="clear-button"
      onClick={handleClick}
      {...props}
    />
  )
}

export type TerminalContentProps = HTMLAttributes<HTMLDivElement>

export function TerminalContent({ children, ...props }: TerminalContentProps) {
  const { output, isStreaming, autoScroll } = useTerminal()
  const containerRef = useRef<HTMLDivElement>(null)

  // biome-ignore lint/correctness/useExhaustiveDependencies: re-run when output changes so the view stays pinned to the bottom
  useEffect(() => {
    if (autoScroll && containerRef.current) {
      containerRef.current.scrollTop = containerRef.current.scrollHeight
    }
  }, [output, autoScroll])

  return (
    <div data-scope="terminal" data-part="content" ref={containerRef} {...props}>
      {children ?? (
        <pre data-part="output">
          <Ansi>{output}</Ansi>
          {isStreaming && <span data-scope="terminal" data-part="cursor" />}
        </pre>
      )}
    </div>
  )
}
