// packages/svelte/src/lib/components/tree-view/tree-view-root-provider.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'
  import type { Snippet } from 'svelte'
  import type { TreeNode } from '../collection/index.ts'
  import type { UseTreeViewReturn } from './use-tree-view.svelte.ts'

  export interface TreeViewRootProviderBaseProps<T extends TreeNode>
    extends RenderStrategyProps, PolymorphicProps<'div'>, RefAttribute {
    value: UseTreeViewReturn<T>
  }
  export interface TreeViewRootProviderProps<T extends TreeNode> extends Assign<
    HTMLProps<'div'>,
    TreeViewRootProviderBaseProps<T>
  > {}

  export type TreeViewRootProviderComponent<P = {}> = <T extends TreeNode>(
    props: Assign<TreeViewRootProviderProps<T>, P>,
  ) => Snippet
</script>

<script lang="ts" generics="T extends TreeNode">
  import {
    RenderStrategyPropsProvider,
    splitRenderStrategyProps,
    type RenderStrategyProps,
  } from '$lib/utils/render-strategy'
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { TreeViewProvider } from './use-tree-view-context.ts'

  let { ref = $bindable(null), value, ...props }: TreeViewRootProviderProps<T> = $props()

  const [renderStrategyProps, treeViewProps] = $derived(splitRenderStrategyProps(props))
  const mergedProps = $derived(mergeProps(value().getRootProps(), treeViewProps))

  TreeViewProvider(() => value())
  RenderStrategyPropsProvider(() => renderStrategyProps)
</script>

<Codesign as="div" bind:ref {...mergedProps} />

// packages/solid/src/components/tree-view/tree-view-root-provider.tsx
import { mergeProps } from '@zag-js/solid'
import type { JSX } from 'solid-js'
import type { Assign } from '../../types.ts'
import { createSplitProps } from '../../utils/create-split-props.ts'
import {
  type RenderStrategyProps,
  RenderStrategyProvider,
  splitRenderStrategyProps,
} from '../../utils/render-strategy.ts'
import type { TreeNode } from '../collection/index.tsx'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import type { UseTreeViewReturn } from './use-tree-view.ts'
import { TreeViewProvider } from './use-tree-view-context.ts'

interface RootProviderProps<T extends TreeNode> {
  value: UseTreeViewReturn<T>
}
export interface TreeViewRootProviderBaseProps<T extends TreeNode>
  extends RootProviderProps<T>, RenderStrategyProps, PolymorphicProps<'div'> {}
export interface TreeViewRootProviderProps<T extends TreeNode>
  extends HTMLProps<'div'>, TreeViewRootProviderBaseProps<T> {}

export const TreeViewRootProvider = <T extends TreeNode>(props: TreeViewRootProviderProps<T>) => {
  const [renderStrategyProps, treeViewProps] = splitRenderStrategyProps(props)
  const [{ value: treeView }, localProps] = createSplitProps<RootProviderProps<T>>()(treeViewProps, ['value'])
  const mergedProps = mergeProps(() => treeView().getRootProps(), localProps)

  return (
    <TreeViewProvider value={treeView}>
      <RenderStrategyProvider value={renderStrategyProps}>
        <codesign.div {...mergedProps} />
      </RenderStrategyProvider>
    </TreeViewProvider>
  )
}

export type TreeViewRootProviderComponent<P = {}> = <T extends TreeNode>(
  props: Assign<TreeViewRootProviderProps<T>, P>,
) => JSX.Element
