// packages/react/src/components/editable/editable-input.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useFieldContext } from '../field/index.ts'
import { useEditableContext } from './use-editable-context.ts'

export interface EditableInputBaseProps extends PolymorphicProps {}
export interface EditableInputProps extends HTMLProps<'input'>, EditableInputBaseProps {}

export const EditableInput = forwardRef<HTMLInputElement, EditableInputProps>((props, ref) => {
  const editable = useEditableContext()
  const mergedProps = mergeProps(editable.getInputProps(), props)
  const field = useFieldContext()

  return <codesign.input aria-describedby={field?.ariaDescribedby} {...mergedProps} ref={ref} />
})

EditableInput.displayName = 'EditableInput'

// packages/svelte/src/lib/components/editable/editable-input.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface EditableInputBaseProps extends PolymorphicProps<'input'>, RefAttribute {}
  export interface EditableInputProps extends Assign<HTMLProps<'input'>, EditableInputBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useEditableContext } from './use-editable-context.ts'

  let { ref = $bindable(null), ...props }: EditableInputProps = $props()

  const editable = useEditableContext()
  const mergedProps = $derived(mergeProps(editable().getInputProps(), props))
</script>

<Codesign as="input" bind:ref {...mergedProps} />
