// packages/react/src/components/editable/editable-preview.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useEditableContext } from './use-editable-context.ts'

export interface EditablePreviewBaseProps extends PolymorphicProps {}
export interface EditablePreviewProps extends HTMLProps<'span'>, EditablePreviewBaseProps {}

export const EditablePreview = forwardRef<HTMLSpanElement, EditablePreviewProps>((props, ref) => {
  const editable = useEditableContext()
  const mergedProps = mergeProps(editable.getPreviewProps(), props)

  return <codesign.span {...mergedProps} ref={ref} />
})

EditablePreview.displayName = 'EditablePreview'

// packages/svelte/src/lib/components/editable/editable-preview.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface EditablePreviewBaseProps extends PolymorphicProps<'span'>, RefAttribute {}
  export interface EditablePreviewProps extends Assign<HTMLProps<'span'>, EditablePreviewBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useEditableContext } from './use-editable-context.ts'

  let { ref = $bindable(null), ...props }: EditablePreviewProps = $props()

  const editable = useEditableContext()
  const mergedProps = $derived(mergeProps(editable().getPreviewProps(), props))
</script>

<Codesign as="span" bind:ref {...mergedProps}>
  {#if props.children}
    {@render props.children()}
  {:else}
    {editable().valueText}
  {/if}
</Codesign>
