// packages/svelte/src/lib/components/select/select-hidden-select.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface SelectHiddenSelectBaseProps extends PolymorphicProps<'select'>, RefAttribute {}
  export interface SelectHiddenSelectProps extends Assign<HTMLProps<'select'>, SelectHiddenSelectBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '$lib/components/factory'
  import { useSelectContext } from './use-select-context.ts'

  let { ref = $bindable(null), ...props }: SelectHiddenSelectProps = $props()
  const select = useSelectContext()
  const mergedProps = $derived(mergeProps(select().getHiddenSelectProps(), props))
</script>

<Codesign as="select" bind:ref {...mergedProps}>
  {#if select().value.length === 0}
    <option value=""></option>
  {/if}
  {#each select().collection.items as item}
    <option value={select().collection.getItemValue(item) ?? ''} disabled={select().collection.getItemDisabled(item)}>
      {select().collection.stringifyItem(item)}
    </option>
  {/each}
</Codesign>

// packages/solid/src/components/select/select-hidden-select.tsx
import { mergeProps } from '@zag-js/solid'
import { Index, Show, createMemo } from 'solid-js'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useFieldContext } from '../field/index.tsx'
import { useSelectContext } from './use-select-context.ts'

export interface SelectHiddenSelectBaseProps extends PolymorphicProps<'select'> {}
export interface SelectHiddenSelectProps extends HTMLProps<'select'>, SelectHiddenSelectBaseProps {}

export const SelectHiddenSelect = (props: SelectHiddenSelectProps) => {
  const select = useSelectContext()
  const mergedProps = mergeProps(() => select().getHiddenSelectProps(), props)
  const isValueEmpty = createMemo(() => select().value.length === 0)
  const field = useFieldContext()

  return (
    <codesign.select aria-describedby={field?.().ariaDescribedby} {...mergedProps}>
      <Show when={isValueEmpty()}>
        <codesign.option value="" />
      </Show>
      <Index each={select().collection.items}>
        {(item) => (
          <codesign.option
            value={select().collection.getItemValue(item()) ?? ''}
            disabled={select().collection.getItemDisabled(item())}
          >
            {select().collection.stringifyItem(item())}
          </codesign.option>
        )}
      </Index>
    </codesign.select>
  )
}
