// packages/svelte/src/lib/components/qr-code/qr-code-root-provider.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, RefAttribute } from '$lib/types'
  import type { UseQrCodeReturn } from './use-qr-code.svelte.ts'

  interface RootProviderProps {
    value: UseQrCodeReturn
  }

  export interface QrCodeRootProviderBaseProps extends RootProviderProps, RefAttribute {}
  export interface QrCodeRootProviderProps extends Assign<HTMLProps<'div'>, QrCodeRootProviderBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { QrCodeProvider } from './use-qr-code-context.ts'

  let { ref = $bindable(null), value, ...props }: QrCodeRootProviderProps = $props()
  const mergedProps = $derived(mergeProps(value().getRootProps(), props))

  QrCodeProvider(() => value())
</script>

<Codesign as="div" bind:ref {...mergedProps} />

// packages/react/src/components/qr-code/qr-code-root-provider.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import type { UseQrCodeReturn } from './use-qr-code.ts'
import { QrCodeProvider } from './use-qr-code-context.ts'

interface RootProviderProps {
  value: UseQrCodeReturn
}

export interface QrCodeRootProviderBaseProps extends RootProviderProps, PolymorphicProps {}
export interface QrCodeRootProviderProps extends HTMLProps<'div'>, QrCodeRootProviderBaseProps {}

const splitRootProviderProps = createSplitProps<RootProviderProps>()

export const QrCodeRootProvider = forwardRef<HTMLDivElement, QrCodeRootProviderProps>((props, ref) => {
  const [{ value: qrCode }, localProps] = splitRootProviderProps(props, ['value'])
  const mergedProps = mergeProps(qrCode.getRootProps(), localProps)

  return (
    <QrCodeProvider value={qrCode}>
      <codesign.div {...mergedProps} ref={ref} />
    </QrCodeProvider>
  )
})

QrCodeRootProvider.displayName = 'QrCodeRootProvider'
