// packages/react/src/components/listbox/listbox-value-text.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useListboxContext } from './use-listbox-context.ts'

export interface ListboxValueTextBaseProps extends PolymorphicProps {
  /**
   * Text to display when no value is listboxed.
   */
  placeholder?: string | undefined
}
export interface ListboxValueTextProps extends HTMLProps<'span'>, ListboxValueTextBaseProps {}

export const ListboxValueText = forwardRef<HTMLSpanElement, ListboxValueTextProps>((props, ref) => {
  const { children, placeholder, ...localprops } = props
  const listbox = useListboxContext()
  const mergedProps = mergeProps(listbox.getValueTextProps(), localprops)

  return (
    <codesign.span {...mergedProps} ref={ref}>
      {children || listbox.valueAsString || placeholder}
    </codesign.span>
  )
})

ListboxValueText.displayName = 'ListboxValueText'

// packages/solid/src/components/listbox/listbox-value-text.tsx
import { mergeProps } from '@zag-js/solid'
import { children } from 'solid-js'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useListboxContext } from './use-listbox-context.ts'

export interface ListboxValueTextBaseProps extends PolymorphicProps<'span'> {
  /**
   * Text to display when no value is selected.
   */
  placeholder?: string
}
export interface ListboxValueTextProps extends HTMLProps<'span'>, ListboxValueTextBaseProps {}

export const ListboxValueText = (props: ListboxValueTextProps) => {
  const { placeholder, ...localprops } = props
  const listbox = useListboxContext()
  const mergedProps = mergeProps(() => listbox().getValueTextProps(), localprops)
  const resolved = children(() => props.children)

  return <codesign.span {...mergedProps}>{resolved() || listbox().valueAsString || placeholder}</codesign.span>
}
