// packages/svelte/src/lib/components/pagination/pagination-item.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'
  import type { ItemProps } from '@zag-js/pagination'

  export interface PaginationItemBaseProps extends ItemProps, PolymorphicProps<'button'>, RefAttribute {}
  export interface PaginationItemProps extends Assign<HTMLProps<'button'>, PaginationItemBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { createSplitProps } from '$lib/utils/create-split-props'
  import { usePaginationContext } from './use-pagination-context.ts'

  let { ref = $bindable(null), ...props }: PaginationItemProps = $props()
  const pagination = usePaginationContext()
  const [itemProps, localProps] = $derived(createSplitProps<ItemProps>()(props, ['value', 'type']))
  const mergedProps = $derived(mergeProps(pagination().getItemProps(itemProps), localProps))
</script>

<Codesign as="button" bind:ref {...mergedProps} />

// packages/vue/src/components/pagination/pagination-item.vue
<script lang="ts">
import type { ItemProps } from '@zag-js/pagination'
import type { ButtonHTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface PaginationItemBaseProps extends ItemProps, PolymorphicProps {}
export interface PaginationItemProps
  extends
    PaginationItemBaseProps,
    /**
     * @vue-ignore
     */
    Omit<ButtonHTMLAttributes, 'type' | 'value'> {}
</script>

<script setup lang="ts">
import { codesign } from '../factory.ts'
import { usePaginationContext } from './use-pagination-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

const props = defineProps<PaginationItemProps>()
const pagination = usePaginationContext()

useForwardExpose()
</script>

<template>
  <codesign.button v-bind="pagination.getItemProps(props)" :as-child="asChild">
    <slot />
  </codesign.button>
</template>
