// packages/react/src/components/signature-pad/signature-pad-segment.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useSignaturePadContext } from './use-signature-pad-context.ts'

export interface SignaturePadSegmentBaseProps extends PolymorphicProps {}
export interface SignaturePadSegmentProps extends HTMLProps<'svg'>, SignaturePadSegmentBaseProps {}

export const SignaturePadSegment = forwardRef<SVGSVGElement, SignaturePadSegmentProps>((props, ref) => {
  const signaturePad = useSignaturePadContext()
  const mergedProps = mergeProps(signaturePad.getSegmentProps(), props)

  return (
    <codesign.svg {...mergedProps} ref={ref}>
      <title>Signature</title>
      {signaturePad.paths.map((path, i) => (
        <path key={i} {...signaturePad.getSegmentPathProps({ path })} />
      ))}
      {signaturePad.currentPath && <path {...signaturePad.getSegmentPathProps({ path: signaturePad.currentPath })} />}
    </codesign.svg>
  )
})

SignaturePadSegment.displayName = 'SignaturePadSegment'

// packages/solid/src/components/signature-pad/signature-pad-segment.tsx
import { mergeProps } from '@zag-js/solid'
import { For, Show } from 'solid-js'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useSignaturePadContext } from './use-signature-pad-context.ts'

export interface SignaturePadSegmentBaseProps extends PolymorphicProps<'svg'> {}
export interface SignaturePadSegmentProps extends HTMLProps<'svg'>, SignaturePadSegmentBaseProps {}

export const SignaturePadSegment = (props: SignaturePadSegmentProps) => {
  const signaturePad = useSignaturePadContext()
  const mergedProps = mergeProps(() => signaturePad().getSegmentProps(), props)

  return (
    <codesign.svg {...mergedProps}>
      <codesign.title>Signature</codesign.title>
      <For each={signaturePad().paths}>
        {(path) => <codesign.path {...signaturePad().getSegmentPathProps({ path })} />}
      </For>
      <Show when={signaturePad().currentPath}>
        {/* @ts-expect-error */}
        <codesign.path {...signaturePad().getSegmentPathProps({ path: signaturePad().currentPath })} />
      </Show>
    </codesign.svg>
  )
}
