// packages/svelte/src/lib/components/tree-view/tree-view-tree.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface TreeViewTreeBaseProps extends PolymorphicProps<'ul'>, RefAttribute {}
  export interface TreeViewTreeProps extends Assign<HTMLProps<'ul'>, TreeViewTreeBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useTreeViewContext } from './use-tree-view-context.ts'

  let { ref = $bindable(null), ...props }: TreeViewTreeProps = $props()

  const treeView = useTreeViewContext()
  const mergedProps = $derived(mergeProps(treeView().getTreeProps(), props))
</script>

<Codesign as="div" bind:ref {...mergedProps} />

// packages/react/src/components/tree-view/tree-view-tree.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useTreeViewContext } from './use-tree-view-context.ts'

export interface TreeViewTreeBaseProps extends PolymorphicProps {}
export interface TreeViewTreeProps extends HTMLProps<'div'>, TreeViewTreeBaseProps {}

export const TreeViewTree = forwardRef<HTMLDivElement, TreeViewTreeProps>((props, ref) => {
  const treeView = useTreeViewContext()
  const mergedProps = mergeProps(treeView.getTreeProps(), props)

  return <codesign.div {...mergedProps} ref={ref} />
})

TreeViewTree.displayName = 'TreeViewTree'
