// packages/react/src/components/scroll-area/scroll-area-thumb.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useScrollAreaContext } from './use-scroll-area-context.ts'
import { useScrollAreaScrollbarContext } from './use-scroll-area-scrollbar-context.ts'

export interface ScrollAreaThumbBaseProps extends PolymorphicProps {}
export interface ScrollAreaThumbProps extends HTMLProps<'div'>, ScrollAreaThumbBaseProps {}

export const ScrollAreaThumb = forwardRef<HTMLDivElement, ScrollAreaThumbProps>((props, ref) => {
  const scrollAreaApi = useScrollAreaContext()
  const scrollbarProps = useScrollAreaScrollbarContext()

  const mergedProps = mergeProps(scrollAreaApi.getThumbProps(scrollbarProps), props)

  return <codesign.div {...mergedProps} ref={ref} />
})

ScrollAreaThumb.displayName = 'ScrollAreaThumb'

// packages/vue/src/components/scroll-area/scroll-area-thumb.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface ScrollAreaThumbBaseProps extends PolymorphicProps {}
export interface ScrollAreaThumbProps
  extends
    ScrollAreaThumbBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { useForwardExpose } from '../../utils/use-forward-expose.ts'
import { codesign } from '../factory.ts'
import { useScrollAreaContext } from './use-scroll-area-context.ts'
import { useScrollAreaScrollbarPropsContext } from './use-scroll-area-scrollbar-props-context.ts'

defineProps<ScrollAreaThumbBaseProps>()

const scrollArea = useScrollAreaContext()
const scrollbarProps = useScrollAreaScrollbarPropsContext()

useForwardExpose()
</script>

<template>
  <codesign.div v-bind="scrollArea.getThumbProps(scrollbarProps)" :as-child="asChild">
    <slot />
  </codesign.div>
</template>
