// packages/solid/src/components/avatar/avatar-image.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useAvatarContext } from './use-avatar-context.ts'

export interface AvatarImageBaseProps extends PolymorphicProps<'img'> {}
export interface AvatarImageProps extends HTMLProps<'img'>, AvatarImageBaseProps {}

export const AvatarImage = (props: AvatarImageProps) => {
  const context = useAvatarContext()
  const mergedProps = mergeProps(() => context().getImageProps(), props)
  return <codesign.img {...mergedProps} />
}

// packages/svelte/src/lib/components/avatar/avatar-image.svelte
<script module lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface AvatarImageBaseProps extends PolymorphicProps<'img'>, RefAttribute {}
  export interface AvatarImageProps extends HTMLProps<'img'>, AvatarImageBaseProps {}
</script>

<script lang="ts">
  import { Codesign } from '../factory/index.ts'
  import { mergeProps } from '@zag-js/svelte'
  import { useAvatarContext } from './use-avatar-context.ts'

  let { ref = $bindable(null), ...props }: AvatarImageProps = $props()
  const avatar = useAvatarContext()
  const mergedProps = $derived(mergeProps(avatar().getImageProps(), props))
</script>

<Codesign as="img" bind:ref {...mergedProps} />
