// packages/svelte/src/lib/components/angle-slider/angle-slider-marker.svelte
<script lang="ts" module>
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'
  import type { MarkerProps } from '@zag-js/angle-slider'

  export interface AngleSliderMarkerBaseProps extends MarkerProps, PolymorphicProps<'span'>, RefAttribute {}
  export interface AngleSliderMarkerProps extends HTMLProps<'span'>, AngleSliderMarkerBaseProps {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { createSplitProps } from '$lib/utils/create-split-props'
  import { Codesign } from '../factory/index.ts'
  import { useAngleSliderContext } from './use-angle-slider-context.ts'

  let { ref = $bindable(null), ...props }: AngleSliderMarkerProps = $props()
  const [markerProps, localProps] = $derived(createSplitProps<MarkerProps>()(props, ['value']))

  const angleSlider = useAngleSliderContext()
  const mergedProps = $derived(mergeProps(angleSlider().getMarkerProps(markerProps), localProps))
</script>

<Codesign as="span" bind:ref {...mergedProps} />

// packages/react/src/components/angle-slider/angle-slider-marker.tsx
'use client'

import type { MarkerProps } from '@zag-js/angle-slider'
import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import type { Assign } from '../../types.ts'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useAngleSliderContext } from './use-angle-slider-context.ts'

export interface AngleSliderMarkerBaseProps extends MarkerProps, PolymorphicProps {}
export interface AngleSliderMarkerProps extends Assign<HTMLProps<'div'>, AngleSliderMarkerBaseProps> {}

const splitMarkerProps = createSplitProps<MarkerProps>()

export const AngleSliderMarker = forwardRef<HTMLDivElement, AngleSliderMarkerProps>((props, ref) => {
  const [markerProps, localProps] = splitMarkerProps(props, ['value'])

  const angleSlider = useAngleSliderContext()
  const mergedProps = mergeProps(angleSlider.getMarkerProps(markerProps), localProps)

  return <codesign.div {...mergedProps} ref={ref} />
})

AngleSliderMarker.displayName = 'AngleSliderMarker'
