// packages/svelte/src/lib/components/drawer/drawer-positioner.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface DrawerPositionerBaseProps extends PolymorphicProps<'div'>, RefAttribute {}
  export interface DrawerPositionerProps extends Assign<HTMLProps<'div'>, DrawerPositionerBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { usePresenceContext } from '../presence/index.ts'
  import { useDrawerContext } from './use-drawer-context.ts'

  let { ref = $bindable(null), ...props }: DrawerPositionerProps = $props()

  const drawer = useDrawerContext()
  const presence = usePresenceContext()
  const mergedProps = $derived(mergeProps(drawer().getPositionerProps(), props))
</script>

{#if !presence().unmounted}
  <Codesign as="div" bind:ref {...mergedProps} />
{/if}

// packages/react/src/components/drawer/drawer-positioner.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { usePresenceContext } from '../presence/index.ts'
import { useDrawerContext } from './use-drawer-context.ts'

export interface DrawerPositionerBaseProps extends PolymorphicProps {}
export interface DrawerPositionerProps extends HTMLProps<'div'>, DrawerPositionerBaseProps {}

export const DrawerPositioner = forwardRef<HTMLDivElement, DrawerPositionerProps>((props, ref) => {
  const drawer = useDrawerContext()
  const presence = usePresenceContext()
  const mergedProps = mergeProps(drawer.getPositionerProps(), props)

  if (presence.unmounted) {
    return null
  }

  return <codesign.div {...mergedProps} ref={ref} />
})

DrawerPositioner.displayName = 'DrawerPositioner'
