// packages/react/src/components/date-picker/date-picker-range-text.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { uniq } from '@zag-js/utils'
import { forwardRef, useMemo } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useDatePickerContext } from './use-date-picker-context.ts'

export interface DatePickerRangeTextBaseProps extends PolymorphicProps {}
export interface DatePickerRangeTextProps extends HTMLProps<'div'>, DatePickerRangeTextBaseProps {}

export const DatePickerRangeText = forwardRef<HTMLDivElement, DatePickerRangeTextProps>((props, ref) => {
  const datePicker = useDatePickerContext()
  const mergedProps = mergeProps(datePicker.getRangeTextProps(), props)
  const visibleRangeText = useMemo(() => {
    const { start, end } = datePicker.visibleRangeText
    return uniq([start, end]).filter(Boolean).join(' - ')
  }, [datePicker.visibleRangeText])

  return (
    <codesign.div {...mergedProps} ref={ref}>
      {visibleRangeText}
    </codesign.div>
  )
})

DatePickerRangeText.displayName = 'DatePickerRangeText'

// packages/solid/src/components/date-picker/date-picker-range-text.tsx
import { mergeProps } from '@zag-js/solid'
import { uniq } from '@zag-js/utils'
import { createMemo } from 'solid-js'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useDatePickerContext } from './use-date-picker-context.ts'

export interface DatePickerRangeTextBaseProps extends PolymorphicProps<'div'> {}
export interface DatePickerRangeTextProps extends HTMLProps<'div'>, DatePickerRangeTextBaseProps {}

export const DatePickerRangeText = (props: DatePickerRangeTextProps) => {
  const api = useDatePickerContext()
  const mergedProps = mergeProps(() => api().getRangeTextProps(), props)
  const visibleRangeText = createMemo(() => {
    const { start, end } = api().visibleRangeText
    return uniq([start, end]).filter(Boolean).join(' - ')
  })

  return <codesign.div {...mergedProps}>{visibleRangeText()}</codesign.div>
}
