// packages/vue/src/components/clipboard/clipboard-input.vue
<script lang="ts">
import type { InputHTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface ClipboardInputBaseProps extends PolymorphicProps {}
export interface ClipboardInputProps
  extends
    ClipboardInputBaseProps,
    /**
     * @vue-ignore
     */
    InputHTMLAttributes {}
</script>

<script setup lang="ts">
import { codesign } from '../factory.ts'
import { useClipboardContext } from './use-clipboard-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

defineProps<ClipboardInputProps>()
const clipboard = useClipboardContext()

useForwardExpose()
</script>

<template>
  <codesign.input v-bind="clipboard.getInputProps()" :as-child="asChild"><slot /></codesign.input>
</template>

// packages/solid/src/components/clipboard/clipboard-input.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useClipboardContext } from './use-clipboard-context.ts'

export interface ClipboardInputBaseProps extends PolymorphicProps<'input'> {}
export interface ClipboardInputProps extends HTMLProps<'input'>, ClipboardInputBaseProps {}

export const ClipboardInput = (props: ClipboardInputProps) => {
  const api = useClipboardContext()
  const mergedProps = mergeProps(() => api().getInputProps(), props)

  return <codesign.input {...mergedProps} />
}
