// packages/react/src/components/clipboard/clipboard-indicator.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { type ReactNode, forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useClipboardContext } from './use-clipboard-context.ts'

export interface ClipboardIndicatorBaseProps extends PolymorphicProps {
  copied?: ReactNode | undefined
}
export interface ClipboardIndicatorProps extends HTMLProps<'div'>, ClipboardIndicatorBaseProps {}

export const ClipboardIndicator = forwardRef<HTMLDivElement, ClipboardIndicatorProps>((props, ref) => {
  const { children, copied, ...localProps } = props
  const clipboard = useClipboardContext()
  const mergedProps = mergeProps(clipboard.getIndicatorProps({ copied: clipboard.copied }), localProps)

  return (
    <codesign.div {...mergedProps} ref={ref}>
      {clipboard.copied ? copied : children}
    </codesign.div>
  )
})

ClipboardIndicator.displayName = 'ClipboardIndicator'

// packages/solid/src/components/clipboard/clipboard-indicator.tsx
import { mergeProps } from '@zag-js/solid'
import { type JSX, Show, children } from 'solid-js'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useClipboardContext } from './use-clipboard-context.ts'

interface IndicatorProps {
  copied?: JSX.Element
}

export interface ClipboardIndicatorBaseProps extends IndicatorProps, PolymorphicProps<'div'> {}
export interface ClipboardIndicatorProps extends HTMLProps<'div'>, ClipboardIndicatorBaseProps {}

export const ClipboardIndicator = (props: ClipboardIndicatorProps) => {
  const [indicatorProps, localProps] = createSplitProps<IndicatorProps>()(props, ['copied'])
  const api = useClipboardContext()
  const mergedProps = mergeProps(api().getIndicatorProps({ copied: api().copied }), localProps)
  const getChildren = children(() => localProps.children)

  return (
    <codesign.div {...mergedProps}>
      <Show when={api().copied} fallback={getChildren()}>
        {indicatorProps.copied}
      </Show>
    </codesign.div>
  )
}
