// packages/svelte/src/lib/components/pagination/pagination-root-provider.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'
  import type { Snippet } from 'svelte'
  import type { UsePaginationReturn } from './use-pagination.svelte.ts'

  export interface RootProviderProps {
    value: UsePaginationReturn
    children?: Snippet
  }

  export interface PaginationRootProviderBaseProps extends PolymorphicProps<'nav'>, RootProviderProps, RefAttribute {}
  export interface PaginationRootProviderProps extends Assign<HTMLProps<'nav'>, PaginationRootProviderBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { PaginationProvider } from './use-pagination-context.ts'

  let { ref = $bindable(null), value, ...props }: PaginationRootProviderProps = $props()

  const mergedProps = $derived(mergeProps(value().getRootProps(), props))

  PaginationProvider(() => value())
</script>

<Codesign as="nav" bind:ref {...mergedProps} />

// packages/react/src/components/pagination/pagination-root-provider.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import type { UsePaginationReturn } from './use-pagination.ts'
import { PaginationProvider } from './use-pagination-context.ts'

interface RootProviderProps {
  value: UsePaginationReturn
}

export interface PaginationRootProviderBaseProps extends RootProviderProps, PolymorphicProps {}
export interface PaginationRootProviderProps extends HTMLProps<'nav'>, PaginationRootProviderBaseProps {}

const splitRootProviderProps = createSplitProps<RootProviderProps>()

export const PaginationRootProvider = forwardRef<HTMLElement, PaginationRootProviderProps>((props, ref) => {
  const [{ value: pagination }, localProps] = splitRootProviderProps(props, ['value'])
  const mergedProps = mergeProps(pagination.getRootProps(), localProps)

  return (
    <PaginationProvider value={pagination}>
      <codesign.nav {...mergedProps} ref={ref} />
    </PaginationProvider>
  )
})

PaginationRootProvider.displayName = 'PaginationRootProvider'
