// packages/solid/src/components/collapsible/collapsible-root.tsx
import { mergeProps } from '@zag-js/solid'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { type UseCollapsibleProps, useCollapsible } from './use-collapsible.ts'
import { CollapsibleProvider } from './use-collapsible-context.ts'

export interface CollapsibleRootBaseProps extends UseCollapsibleProps, PolymorphicProps<'div'> {}
export interface CollapsibleRootProps extends HTMLProps<'div'>, CollapsibleRootBaseProps {}

export const CollapsibleRoot = (props: CollapsibleRootProps) => {
  const [useCollapsibleProps, localProps] = createSplitProps<UseCollapsibleProps>()(props, [
    'collapsedHeight',
    'collapsedWidth',
    'defaultOpen',
    'disabled',
    'id',
    'ids',
    'lazyMount',
    'onExitComplete',
    'onOpenChange',
    'open',
    'unmountOnExit',
  ])

  const api = useCollapsible(useCollapsibleProps)
  const mergedProps = mergeProps(() => api().getRootProps(), localProps)

  return (
    <CollapsibleProvider value={api}>
      <codesign.div {...mergedProps} />
    </CollapsibleProvider>
  )
}

// packages/vue/src/components/collapsible/collapsible-root.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue'
import type { BooleanDefaults } from '../../types.ts'
import type { PolymorphicProps } from '../factory.ts'
import type { RootEmits, RootProps } from './collapsible.types.ts'

export interface CollapsibleRootBaseProps extends RootProps, PolymorphicProps {}
export interface CollapsibleRootProps
  extends
    CollapsibleRootBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
export interface CollapsibleRootEmits extends RootEmits {}
</script>

<script setup lang="ts">
import { codesign } from '../factory.ts'
import { useCollapsible } from './use-collapsible.ts'
import { CollapsibleProvider } from './use-collapsible-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

const props = withDefaults(defineProps<CollapsibleRootProps>(), {
  defaultOpen: undefined,
  disabled: undefined,
  lazyMount: undefined,
  open: undefined,
  unmountOnExit: undefined,
} satisfies BooleanDefaults<RootProps>)

const emits = defineEmits<CollapsibleRootEmits>()

const collapsible = useCollapsible(props, emits)
CollapsibleProvider(collapsible)

useForwardExpose()
</script>

<template>
  <codesign.div v-bind="collapsible.getRootProps()" :as-child="asChild">
    <slot />
  </codesign.div>
</template>
