// packages/react/src/components/password-input/password-input-root-provider.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import type { UsePasswordInputReturn } from './use-password-input.ts'
import { PasswordInputProvider } from './use-password-input-context.ts'

interface RootProviderProps {
  value: UsePasswordInputReturn
}

export interface PasswordInputRootProviderBaseProps extends RootProviderProps, PolymorphicProps {}
export interface PasswordInputRootProviderProps extends HTMLProps<'div'>, PasswordInputRootProviderBaseProps {}

export const PasswordInputRootProvider = forwardRef<HTMLDivElement, PasswordInputRootProviderProps>((props, ref) => {
  const { value: passwordInput, ...localProps } = props
  const mergedProps = mergeProps(passwordInput.getRootProps(), localProps)

  return (
    <PasswordInputProvider value={passwordInput}>
      <codesign.div {...mergedProps} ref={ref} />
    </PasswordInputProvider>
  )
})

PasswordInputRootProvider.displayName = 'PasswordInputRootProvider'

// packages/svelte/src/lib/components/password-input/password-input-root-provider.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'
  import type { UsePasswordInputReturn } from './use-password-input.svelte.ts'

  export interface PasswordInputRootProviderBaseProps extends PolymorphicProps<'div'>, RefAttribute {
    value: UsePasswordInputReturn
  }
  export interface PasswordInputRootProviderProps extends Assign<
    HTMLProps<'div'>,
    PasswordInputRootProviderBaseProps
  > {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { PasswordInputProvider } from './use-password-input-context.ts'

  let { ref = $bindable(null), value, ...props }: PasswordInputRootProviderProps = $props()

  const mergedProps = $derived(mergeProps(value().getRootProps(), props))

  PasswordInputProvider(() => value())
</script>

<Codesign as="div" bind:ref {...mergedProps} />
