// packages/react/src/components/focus-trap/focus-trap.tsx
'use client'

import { type FocusTrapOptions, trapFocus } from '@zag-js/focus-trap'
import { forwardRef, useRef } from 'react'
import type { Assign } from '../../types.ts'
import { useComposedRefs } from '../../utils/compose-refs.ts'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { useSafeLayoutEffect } from '../../utils/use-safe-layout-effect.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'

export interface TrapOptions extends Pick<
  FocusTrapOptions,
  | 'onActivate'
  | 'onDeactivate'
  | 'initialFocus'
  | 'fallbackFocus'
  | 'returnFocusOnDeactivate'
  | 'setReturnFocus'
  | 'persistentElements'
> {
  /**
   * Whether the focus trap is disabled.
   */
  disabled?: boolean | undefined
}

export interface FocusTrapBaseProps extends PolymorphicProps, TrapOptions {}

export interface FocusTrapProps extends Assign<HTMLProps<'div'>, FocusTrapBaseProps> {}

const splitTrapProps = createSplitProps<TrapOptions>()

export const FocusTrap = forwardRef<HTMLDivElement, FocusTrapProps>((props, ref) => {
  const localRef = useRef<HTMLDivElement | null>(null)
  const [trapProps, localProps] = splitTrapProps(props, [
    'disabled',
    'onActivate',
    'onDeactivate',
    'initialFocus',
    'fallbackFocus',
    'returnFocusOnDeactivate',
    'setReturnFocus',
    'persistentElements',
  ])
  const composedRefs = useComposedRefs(localRef, ref)

  useSafeLayoutEffect(() => {
    const node = localRef.current
    if (!node || trapProps.disabled) return
    return trapFocus(node, trapProps)
  }, [ref, trapProps])

  return <codesign.div ref={composedRefs} {...localProps} />
})

FocusTrap.displayName = 'FocusTrap'

// packages/solid/src/components/focus-trap/focus-trap.tsx
import { type FocusTrapOptions, trapFocus } from '@zag-js/focus-trap'
import { createEffect, onCleanup } from 'solid-js'
import type { Assign } from '../../types.ts'
import { composeRefs } from '../../utils/compose-refs.ts'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'

export interface TrapOptions extends Pick<
  FocusTrapOptions,
  | 'onActivate'
  | 'onDeactivate'
  | 'initialFocus'
  | 'fallbackFocus'
  | 'returnFocusOnDeactivate'
  | 'setReturnFocus'
  | 'persistentElements'
> {
  /**
   * Whether the focus trap is disabled.
   */
  disabled?: boolean
}

export interface FocusTrapBaseProps extends PolymorphicProps<'div'>, TrapOptions {}

export interface FocusTrapProps extends Assign<HTMLProps<'div'>, FocusTrapBaseProps> {}

export const FocusTrap = (props: FocusTrapProps) => {
  let localNode!: HTMLDivElement

  const [trapProps, localProps] = createSplitProps<TrapOptions>()(props, [
    'disabled',
    'onActivate',
    'onDeactivate',
    'initialFocus',
    'fallbackFocus',
    'returnFocusOnDeactivate',
    'setReturnFocus',
    'persistentElements',
  ])

  createEffect(() => {
    if (!localNode || trapProps.disabled) return
    const autoFocusNode = localNode.querySelector<HTMLElement>('[autofocus], [data-autofocus]')
    trapProps.initialFocus ||= autoFocusNode ?? undefined
    onCleanup(trapFocus(localNode, trapProps))
  })

  return <codesign.div {...localProps} ref={composeRefs((el) => (localNode = el), props.ref)} />
}
