// packages/react/src/components/timer/timer-separator.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useTimerContext } from './use-timer-context.ts'

export interface TimerSeparatorBaseProps extends PolymorphicProps {}
export interface TimerSeparatorProps extends HTMLProps<'div'>, TimerSeparatorBaseProps {}

export const TimerSeparator = forwardRef<HTMLDivElement, TimerSeparatorProps>((props, ref) => {
  const timer = useTimerContext()

  const mergedProps = mergeProps(timer.getSeparatorProps(), props)

  return <codesign.div {...mergedProps} ref={ref} />
})

TimerSeparator.displayName = 'TimerSeparator'

// packages/svelte/src/lib/components/timer/timer-separator.svelte
<script lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useTimerContext } from './use-timer-context.ts'

  export interface TimerSeparatorBaseProps extends PolymorphicProps<'div'>, RefAttribute {}
  export interface TimerSeparatorProps extends HTMLProps<'div'>, TimerSeparatorBaseProps {}

  let { ref = $bindable(null), ...props }: TimerSeparatorProps = $props()
  const timer = useTimerContext()
  const mergedProps = $derived(mergeProps(timer().getSeparatorProps(), props))
</script>

<Codesign as="div" bind:ref {...mergedProps} />
