// packages/react/src/components/timer/timer-root-provider.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import type { UseTimerReturn } from './use-timer.ts'
import { TimerProvider } from './use-timer-context.ts'

interface RootProviderProps {
  value: UseTimerReturn
}

export interface TimerRootProviderBaseProps extends RootProviderProps, PolymorphicProps {}
export interface TimerRootProviderProps extends HTMLProps<'div'>, TimerRootProviderBaseProps {}

const splitRootProviderProps = createSplitProps<RootProviderProps>()

export const TimerRootProvider = forwardRef<HTMLDivElement, TimerRootProviderProps>((props, ref) => {
  const [{ value: timer }, localProps] = splitRootProviderProps(props, ['value'])
  const mergedProps = mergeProps(timer.getRootProps(), localProps)

  return (
    <TimerProvider value={timer}>
      <codesign.div {...mergedProps} ref={ref} />
    </TimerProvider>
  )
})

TimerRootProvider.displayName = 'TimerRootProvider'

// packages/svelte/src/lib/components/timer/timer-root-provider.svelte
<script lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { TimerProvider } from './use-timer-context.ts'
  import type { UseTimerReturn } from './use-timer.svelte.ts'

  interface RootProviderProps {
    value: UseTimerReturn
  }

  export interface TimerRootProviderBaseProps extends RootProviderProps, PolymorphicProps<'div'>, RefAttribute {}
  export interface TimerRootProviderProps extends HTMLProps<'div'>, TimerRootProviderBaseProps {}

  let { ref = $bindable(null), value, ...props }: TimerRootProviderProps = $props()
  const mergedProps = $derived(mergeProps(value().getRootProps(), props))

  TimerProvider(() => value())
</script>

<Codesign as="div" bind:ref {...mergedProps} />
