// packages/vue/src/components/timer/timer-root-provider.vue
<script lang="ts">
import type { HTMLAttributes, UnwrapRef } from 'vue'
import type { PolymorphicProps } from '../factory.ts'
import type { UseTimerReturn } from './use-timer.ts'

interface RootProviderProps {
  value: UnwrapRef<UseTimerReturn>
}

export interface TimerRootProviderBaseProps extends RootProviderProps, PolymorphicProps {}
export interface TimerRootProviderProps
  extends
    TimerRootProviderBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { codesign } from '../factory.ts'
import { TimerProvider } from './use-timer-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

const props = defineProps<TimerRootProviderProps>()
const timer = computed(() => props.value)

TimerProvider(timer)
useForwardExpose()
</script>

<template>
  <codesign.div v-bind="timer.getRootProps()" :as-child="asChild">
    <slot />
  </codesign.div>
</template>

// packages/svelte/src/lib/components/timer/timer-root-provider.svelte
<script lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { TimerProvider } from './use-timer-context.ts'
  import type { UseTimerReturn } from './use-timer.svelte.ts'

  interface RootProviderProps {
    value: UseTimerReturn
  }

  export interface TimerRootProviderBaseProps extends RootProviderProps, PolymorphicProps<'div'>, RefAttribute {}
  export interface TimerRootProviderProps extends HTMLProps<'div'>, TimerRootProviderBaseProps {}

  let { ref = $bindable(null), value, ...props }: TimerRootProviderProps = $props()
  const mergedProps = $derived(mergeProps(value().getRootProps(), props))

  TimerProvider(() => value())
</script>

<Codesign as="div" bind:ref {...mergedProps} />
