// packages/vue/src/components/toast/toast-description.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface ToastDescriptionBaseProps extends PolymorphicProps {}
export interface ToastDescriptionProps
  extends
    ToastDescriptionBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { codesign } from '../factory.ts'
import { useToastContext } from './use-toast-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

defineProps<ToastDescriptionProps>()
const toast = useToastContext()

useForwardExpose()
</script>

<template>
  <codesign.div v-bind="toast.getDescriptionProps()" :as-child="asChild">
    <slot />
  </codesign.div>
</template>

// packages/solid/src/components/toast/toast-description.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useToastContext } from './use-toast-context.ts'

export interface ToastDescriptionBaseProps extends PolymorphicProps<'div'> {}
export interface ToastDescriptionProps extends HTMLProps<'div'>, ToastDescriptionBaseProps {}

export const ToastDescription = (props: ToastDescriptionProps) => {
  const toast = useToastContext()
  const mergedProps = mergeProps(() => toast().getDescriptionProps(), props)

  return <codesign.div {...mergedProps} />
}
