// packages/react/src/components/field/field-select.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useFieldContext } from './use-field-context.ts'

export interface FieldSelectBaseProps extends PolymorphicProps {}
export interface FieldSelectProps extends HTMLProps<'select'>, FieldSelectBaseProps {}

export const FieldSelect = forwardRef<HTMLSelectElement, FieldSelectProps>((props, ref) => {
  const field = useFieldContext()
  const mergedProps = mergeProps<HTMLProps<'select'>>(field?.getSelectProps(), props)

  return <codesign.select {...mergedProps} ref={ref} />
})

FieldSelect.displayName = 'FieldSelect'

// packages/vue/src/components/field/field-select.vue
<script lang="ts">
import type { SelectHTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface FieldSelectBaseProps extends PolymorphicProps {}
export interface FieldSelectProps
  extends
    FieldSelectBaseProps,
    /**
     * @vue-ignore
     */
    Omit<SelectHTMLAttributes, 'value'> {
  modelValue?: SelectHTMLAttributes['value']
}
</script>

<script setup lang="ts">
import { codesign } from '../factory.ts'
import { useFieldContext } from './use-field-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

defineProps<FieldSelectProps & { modelValue?: string }>()
const field = useFieldContext()

const emit = defineEmits(['update:modelValue'])

useForwardExpose()
</script>

<template>
  <codesign.select
    v-bind="field?.getSelectProps()"
    :value="modelValue"
    @change="(event) => emit('update:modelValue', (event.target as HTMLSelectElement).value)"
    :as-child="asChild"
  >
    <slot />
  </codesign.select>
</template>
