// packages/solid/src/components/progress/progress-view.tsx
import type { ViewProps } from '@zag-js/progress'
import { mergeProps } from '@zag-js/solid'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useProgressContext } from './use-progress-context.ts'

export interface ProgressViewBaseProps extends ViewProps, PolymorphicProps<'span'> {}
export interface ProgressViewProps extends HTMLProps<'span'>, ProgressViewBaseProps {}

export const ProgressView = (props: ProgressViewProps) => {
  const [state, localProps] = createSplitProps<ViewProps>()(props, ['state'])
  const api = useProgressContext()
  const mergedProps = mergeProps(() => api().getViewProps(state), localProps)

  return <codesign.span {...mergedProps} />
}

// packages/svelte/src/lib/components/progress/progress-view.svelte
<script module lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'
  import type { ViewProps } from '@zag-js/progress'

  export interface ProgressViewBaseProps extends ViewProps, PolymorphicProps<'span'>, RefAttribute {}
  export interface ProgressViewProps extends HTMLProps<'span'>, ProgressViewBaseProps {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useProgressContext } from './use-progress-context.ts'

  let { ref = $bindable(null), ...props }: ProgressViewProps = $props()
  const progress = useProgressContext()
  const mergedProps = $derived(mergeProps(progress().getViewProps(props), props))
</script>

<Codesign as="span" bind:ref {...mergedProps} />
