// packages/react/src/components/progress/progress-view.tsx
'use client'

import type { ViewProps } from '@zag-js/progress'
import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useProgressContext } from './use-progress-context.ts'

export interface ProgressViewBaseProps extends ViewProps, PolymorphicProps {}
export interface ProgressViewProps extends HTMLProps<'span'>, ProgressViewBaseProps {}

const splitViewProps = createSplitProps<ViewProps>()

export const ProgressView = forwardRef<HTMLSpanElement, ProgressViewProps>((props, ref) => {
  const [viewProps, localProps] = splitViewProps(props, ['state'])
  const progress = useProgressContext()
  const mergedProps = mergeProps(progress.getViewProps(viewProps), localProps)

  return <codesign.span {...mergedProps} ref={ref} />
})

ProgressView.displayName = 'ProgressView'

// packages/svelte/src/lib/components/progress/progress-view.svelte
<script module lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'
  import type { ViewProps } from '@zag-js/progress'

  export interface ProgressViewBaseProps extends ViewProps, PolymorphicProps<'span'>, RefAttribute {}
  export interface ProgressViewProps extends HTMLProps<'span'>, ProgressViewBaseProps {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useProgressContext } from './use-progress-context.ts'

  let { ref = $bindable(null), ...props }: ProgressViewProps = $props()
  const progress = useProgressContext()
  const mergedProps = $derived(mergeProps(progress().getViewProps(props), props))
</script>

<Codesign as="span" bind:ref {...mergedProps} />
