// packages/react/src/components/progress/progress-range.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useProgressContext } from './use-progress-context.ts'

export interface ProgressRangeBaseProps extends PolymorphicProps {}
export interface ProgressRangeProps extends HTMLProps<'div'>, ProgressRangeBaseProps {}

export const ProgressRange = forwardRef<HTMLDivElement, ProgressRangeProps>((props, ref) => {
  const progress = useProgressContext()
  const mergedProps = mergeProps(progress.getRangeProps(), props)

  return <codesign.div {...mergedProps} ref={ref} />
})

ProgressRange.displayName = 'ProgressRange'

// packages/svelte/src/lib/components/progress/progress-range.svelte
<script module lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface ProgressRangeBaseProps extends PolymorphicProps<'div'>, RefAttribute {}
  export interface ProgressRangeProps extends HTMLProps<'div'>, ProgressRangeBaseProps {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useProgressContext } from './use-progress-context.ts'

  let { ref = $bindable(null), ...props }: ProgressRangeProps = $props()
  const progress = useProgressContext()
  const mergedProps = $derived(mergeProps(progress().getRangeProps(), props))
</script>

<Codesign as="div" bind:ref {...mergedProps} />
