// packages/solid/src/components/listbox/listbox-value-text.tsx
import { mergeProps } from '@zag-js/solid'
import { children } from 'solid-js'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useListboxContext } from './use-listbox-context.ts'

export interface ListboxValueTextBaseProps extends PolymorphicProps<'span'> {
  /**
   * Text to display when no value is selected.
   */
  placeholder?: string
}
export interface ListboxValueTextProps extends HTMLProps<'span'>, ListboxValueTextBaseProps {}

export const ListboxValueText = (props: ListboxValueTextProps) => {
  const { placeholder, ...localprops } = props
  const listbox = useListboxContext()
  const mergedProps = mergeProps(() => listbox().getValueTextProps(), localprops)
  const resolved = children(() => props.children)

  return <codesign.span {...mergedProps}>{resolved() || listbox().valueAsString || placeholder}</codesign.span>
}

// packages/vue/src/components/listbox/listbox-value-text.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface ListboxValueTextBaseProps extends PolymorphicProps {}
export interface ListboxValueTextProps
  extends
    ListboxValueTextBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {
  placeholder?: string
}
</script>

<script setup lang="ts">
import { codesign } from '../factory.ts'
import { useListboxContext } from './use-listbox-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

const props = defineProps<ListboxValueTextProps>()
const listbox = useListboxContext()
const slots = defineSlots()

useForwardExpose()
</script>

<template>
  <codesign.span v-bind="listbox.getValueTextProps()" :as-child="asChild">
    <slot>{{ slots.default?.() || listbox.valueAsString || props.placeholder }}</slot>
  </codesign.span>
</template>
