// packages/react/src/components/qr-code/qr-code-pattern.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useQrCodeContext } from './use-qr-code-context.ts'

export interface QrCodePatternBaseProps extends PolymorphicProps {}
export interface QrCodePatternProps extends HTMLProps<'path'>, QrCodePatternBaseProps {}

export const QrCodePattern = forwardRef<SVGPathElement, QrCodePatternProps>((props, ref) => {
  const qrCode = useQrCodeContext()
  const mergedProps = mergeProps(qrCode.getPatternProps(), props)

  return <codesign.path {...mergedProps} ref={ref} />
})

QrCodePattern.displayName = 'QrCodePattern'

// packages/svelte/src/lib/components/qr-code/qr-code-pattern.svelte
<script module lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface QrCodePatternBaseProps extends PolymorphicProps<'path'>, RefAttribute {}
  export interface QrCodePatternProps extends HTMLProps<'path'>, QrCodePatternBaseProps {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useQrCodeContext } from './use-qr-code-context.ts'

  let { ref = $bindable(null), ...props }: QrCodePatternProps = $props()
  const qrCode = useQrCodeContext()
  const mergedProps = $derived(mergeProps(qrCode().getPatternProps(), props))
</script>

<Codesign as="path" bind:ref {...mergedProps} />
