// packages/vue/src/components/image-cropper/image-cropper-image.vue
<script lang="ts">
import type { ImgHTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface ImageCropperImageBaseProps extends PolymorphicProps {}
export interface ImageCropperImageProps
  extends
    ImageCropperImageBaseProps,
    /**
     * @vue-ignore
     */
    ImgHTMLAttributes {}
</script>

<script setup lang="ts">
import { codesign } from '../factory.ts'
import { useImageCropperContext } from './use-image-cropper-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

defineProps<ImageCropperImageProps>()
const imageCropper = useImageCropperContext()

useForwardExpose()
</script>

<template>
  <codesign.img v-bind="imageCropper.getImageProps()" :as-child="asChild" />
</template>

// packages/react/src/components/image-cropper/image-cropper-image.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useImageCropperContext } from './use-image-cropper-context.ts'

export interface ImageCropperImageBaseProps extends PolymorphicProps {}
export interface ImageCropperImageProps extends HTMLProps<'img'>, ImageCropperImageBaseProps {}

export const ImageCropperImage = forwardRef<HTMLImageElement, ImageCropperImageProps>((props, ref) => {
  const imageCropper = useImageCropperContext()
  const mergedProps = mergeProps(imageCropper.getImageProps(), props)

  return <codesign.img {...mergedProps} ref={ref} />
})

ImageCropperImage.displayName = 'ImageCropperImage'
