// packages/vue/src/components/field/field-required-indicator.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface FieldRequiredIndicatorBaseProps extends PolymorphicProps {}

export interface FieldRequiredIndicatorProps
  extends
    FieldRequiredIndicatorBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { codesign } from '../factory.ts'
import { useFieldContext } from './use-field-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

defineProps<FieldRequiredIndicatorProps>()

const field = useFieldContext()

useForwardExpose()
</script>

<template>
  <codesign.span v-if="field.required" v-bind="field.getRequiredIndicatorProps()" :as-child="asChild">
    <slot>*</slot>
  </codesign.span>
  <slot v-else name="fallback"></slot>
</template>

// packages/react/src/components/field/field-required-indicator.tsx
'use client'

import { mergeProps } from '@zag-js/core'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useFieldContext } from './use-field-context.ts'

export interface FieldRequiredIndicatorBaseProps extends PolymorphicProps {
  fallback?: React.ReactNode | undefined
}
export interface FieldRequiredIndicatorProps extends HTMLProps<'span'>, FieldRequiredIndicatorBaseProps {}

export const FieldRequiredIndicator = forwardRef<HTMLSpanElement, FieldRequiredIndicatorProps>(
  ({ fallback, ...props }, ref) => {
    const field = useFieldContext()

    if (!field.required) {
      return fallback
    }

    const mergedProps = mergeProps(field.getRequiredIndicatorProps(), props)
    return (
      <codesign.span {...mergedProps} ref={ref}>
        {props.children ?? '*'}
      </codesign.span>
    )
  },
)

FieldRequiredIndicator.displayName = 'FieldRequiredIndicator'
