// packages/react/src/ai/sources/sources.tsx
import type { ComponentProps } from 'react'
import { Collapsible } from '../../components/collapsible/index.ts'

export type SourcesProps = ComponentProps<typeof Collapsible.Root>

export function Sources(props: SourcesProps) {
  return <Collapsible.Root data-scope="sources" data-part="root" {...props} />
}

export type SourcesTriggerProps = Omit<ComponentProps<typeof Collapsible.Trigger>, 'onOpenChange'> & {
  count: number
}

export function SourcesTrigger({ children, count, ...props }: SourcesTriggerProps) {
  return (
    <Collapsible.Trigger data-scope="sources" data-part="trigger" {...props}>
      {children ?? <p data-part="count">Used {count} sources</p>}
    </Collapsible.Trigger>
  )
}

export type SourcesContentProps = ComponentProps<typeof Collapsible.Content>

export function SourcesContent(props: SourcesContentProps) {
  return <Collapsible.Content data-scope="sources" data-part="content" {...props} />
}

export type SourceProps = ComponentProps<'a'>

export function Source({ href, title, children, ...props }: SourceProps) {
  return (
    <a data-scope="sources" data-part="source" href={href} rel="noreferrer" target="_blank" {...props}>
      {children ?? <span>{title}</span>}
    </a>
  )
}

// packages/solid/src/ai/sources/sources.tsx
import { splitProps } from 'solid-js'
import type { JSX } from 'solid-js'
import { Collapsible } from '../../components/collapsible/index.ts'

export type SourcesProps = JSX.HTMLAttributes<HTMLDivElement>

export function Sources(props: SourcesProps) {
  return <Collapsible.Root data-scope="sources" data-part="root" {...props} />
}

export type SourcesTriggerProps = JSX.HTMLAttributes<HTMLButtonElement> & {
  count: number
}

export function SourcesTrigger(props: SourcesTriggerProps) {
  const [local, rest] = splitProps(props, ['children', 'count'])

  return (
    <Collapsible.Trigger data-scope="sources" data-part="trigger" {...rest}>
      {local.children ?? (
        <p data-scope="sources" data-part="count">
          Used {local.count} sources
        </p>
      )}
    </Collapsible.Trigger>
  )
}

export type SourcesContentProps = JSX.HTMLAttributes<HTMLDivElement>

export function SourcesContent(props: SourcesContentProps) {
  return <Collapsible.Content data-scope="sources" data-part="content" {...props} />
}

export type SourceProps = JSX.HTMLAttributes<HTMLAnchorElement> & {
  href?: string
  title?: string
}

export function Source(props: SourceProps) {
  const [local, rest] = splitProps(props, ['children', 'href', 'title'])

  return (
    <a data-scope="sources" data-part="source" href={local.href} rel="noreferrer" target="_blank" {...rest}>
      {local.children ?? <span>{local.title}</span>}
    </a>
  )
}
