// packages/svelte/src/lib/components/slider/slider-hidden-input.svelte
<script module lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface SliderHiddenInputBaseProps extends PolymorphicProps<'input'>, RefAttribute {}
  export interface SliderHiddenInputProps extends HTMLProps<'input'>, SliderHiddenInputBaseProps {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useSliderContext } from './use-slider-context.ts'
  import { useSliderThumbPropsContext } from './use-slider-thumb-props-context.ts'

  let { ref = $bindable(null), ...props }: SliderHiddenInputProps = $props()
  const slider = useSliderContext()
  const thumbProps = useSliderThumbPropsContext()
  const mergedProps = $derived(mergeProps(slider().getHiddenInputProps(thumbProps()), props))
</script>

<Codesign as="input" bind:ref {...mergedProps} />

// packages/react/src/components/slider/slider-hidden-input.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useSliderContext } from './use-slider-context.ts'
import { useSliderThumbPropsContext } from './use-slider-thumb-props-context.ts'

export interface SliderHiddenInputBaseProps extends PolymorphicProps {}
export interface SliderHiddenInputProps extends HTMLProps<'input'>, SliderHiddenInputBaseProps {}

export const SliderHiddenInput = forwardRef<HTMLInputElement, SliderHiddenInputProps>((props, ref) => {
  const slider = useSliderContext()
  const thumbProps = useSliderThumbPropsContext()
  const mergedProps = mergeProps(slider.getHiddenInputProps(thumbProps), props)

  return <codesign.input {...mergedProps} ref={ref} />
})

SliderHiddenInput.displayName = 'SliderHiddenInput'
