// packages/svelte/src/lib/components/timer/timer-action-trigger.svelte
<script lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'
  import { mergeProps } from '@zag-js/svelte'
  import type { ActionTriggerProps } from '@zag-js/timer'
  import { Codesign } from '../factory/index.ts'
  import { useTimerContext } from './use-timer-context.ts'

  export interface TimerActionTriggerBaseProps extends ActionTriggerProps, PolymorphicProps<'button'>, RefAttribute {}

  export interface TimerActionTriggerProps extends HTMLProps<'button'>, TimerActionTriggerBaseProps {}

  let { ref = $bindable(null), ...props }: TimerActionTriggerProps = $props()

  const timer = useTimerContext()
  const mergedProps = $derived(mergeProps(timer().getActionTriggerProps(props), props))
</script>

<Codesign as="button" bind:ref {...mergedProps} />

// packages/solid/src/components/timer/timer-action-trigger.tsx
import { mergeProps } from '@zag-js/solid'
import type { ActionTriggerProps } from '@zag-js/timer'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useTimerContext } from './use-timer-context.ts'

export interface TimerActionTriggerBaseProps extends ActionTriggerProps, PolymorphicProps<'button'> {}
export interface TimerActionTriggerProps extends HTMLProps<'button'>, TimerActionTriggerBaseProps {}

export const TimerActionTrigger = (props: TimerActionTriggerProps) => {
  const [actionTriggerProps, localProps] = createSplitProps<ActionTriggerProps>()(props, ['action'])
  const timer = useTimerContext()
  const mergedProps = mergeProps(() => timer().getActionTriggerProps(actionTriggerProps), localProps)

  return <codesign.button {...mergedProps} />
}
