// packages/svelte/src/lib/components/timer/timer-control.svelte
<script lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useTimerContext } from './use-timer-context.ts'

  export interface TimerControlBaseProps extends PolymorphicProps<'div'>, RefAttribute {}
  export interface TimerControlProps extends HTMLProps<'div'>, TimerControlBaseProps {}

  let { ref = $bindable(null), ...props }: TimerControlProps = $props()
  const timer = useTimerContext()
  const mergedProps = $derived(mergeProps(timer().getControlProps(), props))
</script>

<Codesign as="div" bind:ref {...mergedProps} />

// packages/solid/src/components/timer/timer-control.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useTimerContext } from './use-timer-context.ts'

export interface TimerControlBaseProps extends PolymorphicProps<'div'> {}
export interface TimerControlProps extends HTMLProps<'div'>, TimerControlBaseProps {}

export const TimerControl = (props: TimerControlProps) => {
  const timer = useTimerContext()
  const mergedProps = mergeProps(() => timer().getControlProps(), props)

  return <codesign.div {...mergedProps} />
}
