// packages/react/src/components/navigation-menu/navigation-menu-item.tsx
'use client'

import type { ItemProps } from '@zag-js/navigation-menu'
import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useNavigationMenuContext } from './use-navigation-menu-context.ts'
import { NavigationMenuItemPropsProvider } from './use-navigation-menu-item-props-context.ts'

export interface NavigationMenuItemBaseProps extends ItemProps, PolymorphicProps {}
export interface NavigationMenuItemProps extends HTMLProps<'div'>, NavigationMenuItemBaseProps {}

const splitItemProps = createSplitProps<ItemProps>()

export const NavigationMenuItem = forwardRef<HTMLDivElement, NavigationMenuItemProps>((props, ref) => {
  const [itemProps, localProps] = splitItemProps(props, ['disabled', 'value'])
  const navigationMenu = useNavigationMenuContext()
  const mergedProps = mergeProps(navigationMenu.getItemProps(itemProps), localProps)

  return (
    <NavigationMenuItemPropsProvider value={itemProps}>
      <codesign.div {...mergedProps} ref={ref} />
    </NavigationMenuItemPropsProvider>
  )
})

NavigationMenuItem.displayName = 'NavigationMenuItem'

// packages/vue/src/components/navigation-menu/navigation-menu-item.vue
<script lang="ts">
import type { ItemProps } from '@zag-js/navigation-menu'
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface NavigationMenuItemBaseProps extends ItemProps, PolymorphicProps {}
export interface NavigationMenuItemProps
  extends
    NavigationMenuItemBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { codesign } from '../factory.ts'
import { useNavigationMenuContext } from './use-navigation-menu-context.ts'
import { NavigationMenuItemPropsProvider } from './use-navigation-menu-item-props-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

const props = defineProps<NavigationMenuItemProps>()
const navigationMenu = useNavigationMenuContext()

const itemProps = computed(() => ({ value: props.value, disabled: props.disabled }))
NavigationMenuItemPropsProvider(itemProps)

useForwardExpose()
</script>

<template>
  <codesign.div v-bind="navigationMenu.getItemProps(props)" :as-child="asChild">
    <slot />
  </codesign.div>
</template>
