// packages/solid/src/components/tour/tour-action-trigger.tsx
import { mergeProps } from '@zag-js/solid'
import type { StepActionTriggerProps } from '@zag-js/tour'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useTourContext } from './use-tour-context.ts'

export interface TourActionTriggerBaseProps extends PolymorphicProps<'button'>, StepActionTriggerProps {}
export interface TourActionTriggerProps extends HTMLProps<'button'>, TourActionTriggerBaseProps {}

export const TourActionTrigger = (props: TourActionTriggerProps) => {
  const [actionTriggerProps, localProps] = createSplitProps<StepActionTriggerProps>()(props, ['action'])
  const tour = useTourContext()
  const mergedProps = mergeProps(() => tour().getActionTriggerProps(actionTriggerProps), localProps)

  return <codesign.button {...mergedProps}>{mergedProps.children || actionTriggerProps.action.label}</codesign.button>
}

// packages/vue/src/components/tour/tour-action-trigger.vue
<script lang="ts">
import type { StepActionTriggerProps } from '@zag-js/tour'
import type { ButtonHTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface TourActionTriggerBaseProps extends StepActionTriggerProps, PolymorphicProps {}
export interface TourActionTriggerProps
  extends
    TourActionTriggerBaseProps,
    /**
     * @vue-ignore
     */
    ButtonHTMLAttributes {}
</script>

<script setup lang="ts">
import { codesign } from '../factory.ts'
import { useTourContext } from './use-tour-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

const props = defineProps<TourActionTriggerBaseProps>()
const tour = useTourContext()
const slots = defineSlots()

useForwardExpose()
</script>

<template>
  <codesign.button v-bind="tour.getActionTriggerProps(props)" :as-child="asChild">
    <slot>{{ slots.default?.() || props.action.label }}</slot>
  </codesign.button>
</template>
