// packages/svelte/src/lib/components/collapsible/examples/basic.svelte
<script lang="ts">
  import { Collapsible } from '@codesign-ui/svelte/collapsible'
  import { ChevronRightIcon } from 'lucide-svelte'
  import styles from 'styles/collapsible.module.css'
</script>

<Collapsible.Root class={styles.Root}>
  <Collapsible.Trigger class={styles.Trigger}>
    What is Codesign UI?
    <Collapsible.Indicator class={styles.Indicator}>
      <ChevronRightIcon />
    </Collapsible.Indicator>
  </Collapsible.Trigger>
  <Collapsible.Content class={styles.Content}>
    <div class={styles.Body}>
      Codesign UI is a headless component library for building accessible, high-quality UI components for React, Solid,
      Vue, and Svelte.
    </div>
  </Collapsible.Content>
</Collapsible.Root>

// packages/react/src/components/highlight/examples/basic.tsx
import { Highlight } from '@codesign-ui/react/highlight'
import styles from 'styles/highlight.module.css'

export const Basic = () => (
  <p className={styles.Text}>
    <Highlight
      className={styles.Mark}
      query="component"
      text="Codesign UI is a headless component library for building accessible web applications."
    />
  </p>
)
