// packages/svelte/src/lib/components/tour/tour-title.svelte
<script module lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface TourTitleBaseProps extends PolymorphicProps<'h2'>, RefAttribute {}
  export interface TourTitleProps extends HTMLProps<'h2'>, TourTitleBaseProps {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useTourContext } from './use-tour-context.ts'

  let { ref = $bindable(null), ...props }: TourTitleProps = $props()

  const tour = useTourContext()

  const mergedProps = $derived(mergeProps(tour().getTitleProps(), props))
</script>

<Codesign as="h2" bind:ref {...mergedProps}>
  {#if props.children}
    {@render props.children()}
  {:else}
    {tour().step?.title}
  {/if}
</Codesign>

// packages/react/src/components/tour/tour-title.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useTourContext } from './use-tour-context.ts'

export interface TourTitleBaseProps extends PolymorphicProps {}
export interface TourTitleProps extends HTMLProps<'h2'>, TourTitleBaseProps {}

export const TourTitle = forwardRef<HTMLHeadingElement, TourTitleProps>((props, ref) => {
  const tour = useTourContext()
  const mergedProps = mergeProps(tour.getTitleProps(), props)

  return (
    <codesign.h2 {...mergedProps} ref={ref}>
      {mergedProps.children || tour.step?.title}
    </codesign.h2>
  )
})

TourTitle.displayName = 'TourTitle'
