// packages/svelte/src/lib/components/tour/tour-progress-text.svelte
<script module lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface TourProgressTextBaseProps extends PolymorphicProps<'div'>, RefAttribute {}
  export interface TourProgressTextProps extends HTMLProps<'div'>, TourProgressTextBaseProps {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useTourContext } from './use-tour-context.ts'

  let { ref = $bindable(null), ...props }: TourProgressTextProps = $props()

  const tour = useTourContext()

  const mergedProps = $derived(mergeProps(tour().getProgressTextProps(), props))
</script>

<Codesign as="div" bind:ref {...mergedProps}>
  {#if props.children}
    {@render props.children()}
  {:else}
    {tour().getProgressText()}
  {/if}
</Codesign>

// packages/react/src/components/tour/tour-progress-text.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useTourContext } from './use-tour-context.ts'

export interface TourProgressTextBaseProps extends PolymorphicProps {}
export interface TourProgressTextProps extends HTMLProps<'div'>, TourProgressTextBaseProps {}

export const TourProgressText = forwardRef<HTMLDivElement, TourProgressTextProps>((props, ref) => {
  const tour = useTourContext()
  const mergedProps = mergeProps(tour.getProgressTextProps(), props)

  return (
    <codesign.div {...mergedProps} ref={ref}>
      {mergedProps.children || tour.getProgressText()}
    </codesign.div>
  )
})

TourProgressText.displayName = 'TourProgressText'
