// packages/svelte/src/lib/components/avatar/avatar-image.svelte
<script module lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface AvatarImageBaseProps extends PolymorphicProps<'img'>, RefAttribute {}
  export interface AvatarImageProps extends HTMLProps<'img'>, AvatarImageBaseProps {}
</script>

<script lang="ts">
  import { Codesign } from '../factory/index.ts'
  import { mergeProps } from '@zag-js/svelte'
  import { useAvatarContext } from './use-avatar-context.ts'

  let { ref = $bindable(null), ...props }: AvatarImageProps = $props()
  const avatar = useAvatarContext()
  const mergedProps = $derived(mergeProps(avatar().getImageProps(), props))
</script>

<Codesign as="img" bind:ref {...mergedProps} />

// packages/react/src/components/avatar/avatar-image.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useAvatarContext } from './use-avatar-context.ts'

export interface AvatarImageBaseProps extends PolymorphicProps {}
export interface AvatarImageProps extends HTMLProps<'img'>, AvatarImageBaseProps {}

export const AvatarImage = forwardRef<HTMLImageElement, AvatarImageProps>((props, ref) => {
  const avatar = useAvatarContext()
  const mergedProps = mergeProps(avatar.getImageProps(), props)

  return <codesign.img {...mergedProps} ref={ref} />
})

AvatarImage.displayName = 'AvatarImage'
