// packages/svelte/src/lib/components/avatar/avatar-fallback.svelte
<script module lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface AvatarFallbackBaseProps extends PolymorphicProps<'span'>, RefAttribute {}
  export interface AvatarFallbackProps extends HTMLProps<'span'>, AvatarFallbackBaseProps {}
</script>

<script lang="ts">
  import { useAvatarContext } from './use-avatar-context.ts'
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'

  let { ref = $bindable(null), ...props }: AvatarFallbackProps = $props()

  const avatar = useAvatarContext()
  const mergedProps = $derived(mergeProps(avatar().getFallbackProps(), props))
</script>

<Codesign as="span" bind:ref {...mergedProps} />

// packages/react/src/components/avatar/avatar-fallback.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useAvatarContext } from './use-avatar-context.ts'

export interface AvatarFallbackBaseProps extends PolymorphicProps {}
export interface AvatarFallbackProps extends HTMLProps<'span'>, AvatarFallbackBaseProps {}

export const AvatarFallback = forwardRef<HTMLSpanElement, AvatarFallbackProps>((props, ref) => {
  const avatar = useAvatarContext()
  const mergedProps = mergeProps(avatar.getFallbackProps(), props)

  return <codesign.span {...mergedProps} ref={ref} />
})

AvatarFallback.displayName = 'AvatarFallback'
