// packages/solid/src/components/radio-group/radio-group-root.tsx
import { mergeProps } from '@zag-js/solid'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { type UseRadioGroupProps, useRadioGroup } from './use-radio-group.ts'
import { RadioGroupProvider } from './use-radio-group-context.ts'

export interface RadioGroupRootBaseProps extends UseRadioGroupProps, PolymorphicProps<'div'> {}
export interface RadioGroupRootProps extends HTMLProps<'div'>, RadioGroupRootBaseProps {}

export const RadioGroupRoot = (props: RadioGroupRootProps) => {
  const [useRadioGroupProps, localProps] = createSplitProps<UseRadioGroupProps>()(props, [
    'defaultValue',
    'disabled',
    'form',
    'id',
    'ids',
    'invalid',
    'name',
    'onValueChange',
    'orientation',
    'readOnly',
    'required',
    'value',
  ])

  const radioGroup = useRadioGroup(useRadioGroupProps)
  const mergedProps = mergeProps(() => radioGroup().getRootProps(), localProps)

  return (
    <RadioGroupProvider value={radioGroup}>
      <codesign.div {...mergedProps} />
    </RadioGroupProvider>
  )
}

// packages/svelte/src/lib/components/radio-group/radio-group-root.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'
  import type { ValueChangeDetails } from '@zag-js/radio-group'
  import type { UseRadioGroupProps } from './use-radio-group.svelte.ts'

  export interface RadioGroupRootEmits {
    valueChange: ValueChangeDetails
  }

  export interface RadioGroupRootBaseProps extends UseRadioGroupProps, PolymorphicProps<'div'>, RefAttribute {}
  export interface RadioGroupRootProps extends Assign<HTMLProps<'div'>, RadioGroupRootBaseProps> {}
</script>

<script lang="ts">
  import { createSplitProps } from '$lib/utils/create-split-props'
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { RadioGroupProvider } from './use-radio-group-context.ts'
  import { useRadioGroup } from './use-radio-group.svelte.ts'

  let { ref = $bindable(null), value = $bindable(), ...props }: RadioGroupRootProps = $props()
  const providedId = $props.id()

  const [radioGroupProps, localProps] = $derived(
    createSplitProps<UseRadioGroupProps>()(props, [
      'defaultValue',
      'disabled',
      'form',
      'id',
      'ids',
      'invalid',
      'name',
      'onValueChange',
      'orientation',
      'readOnly',
      'required',
      'value',
    ]),
  )

  const resolvedProps = $derived<UseRadioGroupProps>({
    ...radioGroupProps,
    id: radioGroupProps.id ?? providedId,
    value,
    onValueChange(details) {
      radioGroupProps.onValueChange?.(details)
      if (value !== undefined) value = details.value
    },
  })

  const radioGroup = useRadioGroup(() => resolvedProps)
  const mergedProps = $derived(mergeProps(radioGroup().getRootProps(), localProps))

  RadioGroupProvider(radioGroup)
</script>

<Codesign as="div" bind:ref {...mergedProps} />
