// packages/solid/src/components/steps/steps-list.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useStepsContext } from './use-steps-context.ts'

export interface StepsListBaseProps extends PolymorphicProps<'div'> {}
export interface StepsListProps extends HTMLProps<'div'>, StepsListBaseProps {}

export const StepsList = (props: StepsListProps) => {
  const steps = useStepsContext()
  const mergedProps = mergeProps(() => steps().getListProps(), props)

  return <codesign.div {...mergedProps} />
}

// packages/vue/src/components/steps/steps-list.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface StepsListBaseProps extends PolymorphicProps {}
export interface StepsListProps
  extends
    StepsListBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { codesign } from '../factory.ts'
import { useStepsContext } from './use-steps-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

defineProps<StepsListProps>()
const steps = useStepsContext()

useForwardExpose()
</script>

<template>
  <codesign.div v-bind="steps.getListProps()" :as-child="asChild">
    <slot />
  </codesign.div>
</template>
