// packages/solid/src/components/color-picker/color-picker-format-select.tsx
import { mergeProps } from '@zag-js/solid'
import { Index } from 'solid-js'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useColorPickerContext } from './use-color-picker-context.ts'

export interface ColorPickerFormatSelectBaseProps extends PolymorphicProps<'select'> {}
export interface ColorPickerFormatSelectProps extends HTMLProps<'select'>, ColorPickerFormatSelectBaseProps {}

export const ColorPickerFormatSelect = (props: ColorPickerFormatSelectProps) => {
  const api = useColorPickerContext()
  const mergedProps = mergeProps(() => api().getFormatSelectProps(), props)

  return (
    <codesign.select {...mergedProps}>
      <Index each={['rgba', 'hsla', 'hsba']}>{(format) => <codesign.option value={format()}>{format()}</codesign.option>}</Index>
    </codesign.select>
  )
}

// packages/svelte/src/lib/components/color-picker/color-picker-format-select.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface ColorPickerFormatSelectBaseProps extends PolymorphicProps<'select'>, RefAttribute {}
  export interface ColorPickerFormatSelectProps extends Assign<HTMLProps<'select'>, ColorPickerFormatSelectBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useColorPickerContext } from './use-color-picker-context.ts'

  let { ref = $bindable(null), ...props }: ColorPickerFormatSelectProps = $props()

  const colorPicker = useColorPickerContext()
  const mergedProps = $derived(mergeProps(colorPicker().getFormatSelectProps(), props))
</script>

<Codesign as="select" bind:ref {...mergedProps} value={colorPicker().format}>
  {#each ['rgba', 'hsla', 'hsba'] as format}
    <option value={format}>{format}</option>
  {/each}
</Codesign>
