// packages/react/src/components/color-picker/color-picker-swatch-trigger.tsx
'use client'

import type { SwatchTriggerProps } from '@zag-js/color-picker'
import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import type { Assign } from '../../types.ts'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useColorPickerContext } from './use-color-picker-context.ts'

export interface ColorPickerSwatchTriggerBaseProps extends SwatchTriggerProps, PolymorphicProps {}
export interface ColorPickerSwatchTriggerProps extends Assign<HTMLProps<'button'>, ColorPickerSwatchTriggerBaseProps> {}

const splitSwatchTriggerProps = createSplitProps<SwatchTriggerProps>()

export const ColorPickerSwatchTrigger = forwardRef<HTMLButtonElement, ColorPickerSwatchTriggerProps>((props, ref) => {
  const [triggerProps, localProps] = splitSwatchTriggerProps(props, ['value', 'disabled'])
  const colorPicker = useColorPickerContext()
  const mergedProps = mergeProps(colorPicker.getSwatchTriggerProps(triggerProps), localProps)

  return <codesign.button {...mergedProps} ref={ref} />
})

ColorPickerSwatchTrigger.displayName = 'ColorPickerSwatchTrigger'

// packages/svelte/src/lib/components/color-picker/color-picker-swatch-trigger.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'
  import type { SwatchTriggerProps } from '@zag-js/color-picker'

  export interface ColorPickerSwatchTriggerBaseProps
    extends SwatchTriggerProps, PolymorphicProps<'button'>, RefAttribute {}
  export interface ColorPickerSwatchTriggerProps extends Assign<
    HTMLProps<'button'>,
    ColorPickerSwatchTriggerBaseProps
  > {}
</script>

<script lang="ts">
  import { createSplitProps } from '$lib/utils/create-split-props'
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useColorPickerContext } from './use-color-picker-context.ts'

  let { ref = $bindable(null), ...props }: ColorPickerSwatchTriggerProps = $props()

  const [swatchTriggerProps, localProps] = $derived(
    createSplitProps<SwatchTriggerProps>()(props, ['value', 'disabled']),
  )

  const colorPicker = useColorPickerContext()
  const mergedProps = $derived(mergeProps(colorPicker().getSwatchTriggerProps(swatchTriggerProps), localProps))
</script>

<Codesign as="button" bind:ref {...mergedProps} />
