// packages/solid/src/components/menu/menu-trigger-item.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useMenuTriggerItemContext } from './use-menu-trigger-item-context.ts'
import { MenuItemPropsProvider } from './use-menu-option-item-props-context.ts'

export interface MenuTriggerItemBaseProps extends PolymorphicProps<'div'> {}
export interface MenuTriggerItemProps extends HTMLProps<'div'>, MenuTriggerItemBaseProps {}

export const MenuTriggerItem = (props: MenuTriggerItemProps) => {
  const getTriggerItemProps = useMenuTriggerItemContext()
  const mergedProps = mergeProps(() => getTriggerItemProps?.(), props)
  return (
    <MenuItemPropsProvider value={{ value: mergedProps['data-value'] }}>
      <codesign.div {...mergedProps} />
    </MenuItemPropsProvider>
  )
}

// packages/vue/src/components/menu/menu-trigger-item.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'
import { useMenuTriggerItemContext } from './use-menu-trigger-item-context.ts'

export interface MenuTriggerItemBaseProps extends PolymorphicProps {}
export interface MenuTriggerItemProps
  extends
    MenuTriggerItemBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { codesign } from '../factory.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'
import { MenuItemPropsProvider } from './use-menu-option-item-props-context.ts'

defineProps<MenuTriggerItemProps>()
const triggerItemProps = useMenuTriggerItemContext()

MenuItemPropsProvider(computed(() => ({ value: (triggerItemProps.value as any)?.['data-value'] })))

useForwardExpose()
</script>

<template>
  <codesign.div v-bind="triggerItemProps" :as-child="asChild">
    <slot />
  </codesign.div>
</template>
