// packages/react/src/ai/chain-of-thought/chain-of-thought.tsx
import type { ComponentProps, ReactNode } from 'react'
import { createContext, useContext, useMemo } from 'react'
import { Collapsible } from '../../components/collapsible/index.ts'
import { useControllableState } from '../use-controllable-state.ts'

const SCOPE = 'chain-of-thought'

interface ChainOfThoughtContextValue {
  isOpen: boolean
  setIsOpen: (open: boolean) => void
}

const ChainOfThoughtContext = createContext<ChainOfThoughtContextValue | null>(null)

function useChainOfThought() {
  const context = useContext(ChainOfThoughtContext)
  if (!context) {
    throw new Error('ChainOfThought components must be used within ChainOfThought')
  }
  return context
}

export type ChainOfThoughtProps = ComponentProps<'div'> & {
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
}

export function ChainOfThought({ open, defaultOpen = false, onOpenChange, children, ...props }: ChainOfThoughtProps) {
  const [isOpen, setIsOpen] = useControllableState({
    defaultValue: defaultOpen,
    onChange: onOpenChange,
    value: open,
  })

  const contextValue = useMemo<ChainOfThoughtContextValue>(() => ({ isOpen, setIsOpen }), [isOpen, setIsOpen])

  return (
    <ChainOfThoughtContext.Provider value={contextValue}>
      <div data-scope="chain-of-thought" data-part="root" {...props}>
        {children}
      </div>
    </ChainOfThoughtContext.Provider>
  )
}

export type ChainOfThoughtHeaderProps = ComponentProps<'button'> & {
  indicator?: ReactNode
}

export function ChainOfThoughtHeader({ children, indicator, ...props }: ChainOfThoughtHeaderProps) {
  const { isOpen, setIsOpen } = useChainOfThought()

  return (
    <Collapsible.Root onOpenChange={(details) => setIsOpen(details.open)} open={isOpen}>
      <Collapsible.Trigger data-scope={SCOPE} data-part="trigger" {...props}>
        {children ?? 'Chain of Thought'}
        {indicator}
      </Collapsible.Trigger>
    </Collapsible.Root>
  )
}

export type ChainOfThoughtStepProps = ComponentProps<'div'> & {
  icon?: ReactNode
  label: ReactNode
  description?: ReactNode
  status?: 'complete' | 'active' | 'pending'
}

export function ChainOfThoughtStep({
  icon,
  label,
  description,
  status = 'complete',
  children,
  ...props
}: ChainOfThoughtStepProps) {
  return (
    <div data-scope={SCOPE} data-part="step" data-status={status} {...props}>
      <div data-scope={SCOPE} data-part="step-marker">
        {icon}
      </div>
      <div data-scope={SCOPE} data-part="step-body">
        <div data-scope={SCOPE} data-part="step-label">
          {label}
        </div>
        {description && (
          <div data-scope={SCOPE} data-part="step-description">
            {description}
          </div>
        )}
        {children}
      </div>
    </div>
  )
}

export type ChainOfThoughtSearchResultsProps = ComponentProps<'div'>

export function ChainOfThoughtSearchResults(props: ChainOfThoughtSearchResultsProps) {
  return <div data-scope="chain-of-thought" data-part="search-results" {...props} />
}

export type ChainOfThoughtSearchResultProps = ComponentProps<'span'>

export function ChainOfThoughtSearchResult(props: ChainOfThoughtSearchResultProps) {
  return <span data-scope="chain-of-thought" data-part="search-result" {...props} />
}

export type ChainOfThoughtContentProps = ComponentProps<typeof Collapsible.Content>

export function ChainOfThoughtContent(props: ChainOfThoughtContentProps) {
  const { isOpen } = useChainOfThought()

  return (
    <Collapsible.Root open={isOpen}>
      <Collapsible.Content data-scope="chain-of-thought" data-part="content" {...props} />
    </Collapsible.Root>
  )
}

export type ChainOfThoughtImageProps = ComponentProps<'div'> & {
  caption?: string
}

export function ChainOfThoughtImage({ caption, children, ...props }: ChainOfThoughtImageProps) {
  return (
    <div data-scope={SCOPE} data-part="image" {...props}>
      <div data-scope={SCOPE} data-part="image-frame">
        {children}
      </div>
      {caption && (
        <p data-scope={SCOPE} data-part="image-caption">
          {caption}
        </p>
      )}
    </div>
  )
}

// packages/solid/src/ai/chain-of-thought/chain-of-thought.tsx
import { Show, createSignal, splitProps } from 'solid-js'
import type { JSX } from 'solid-js'
import { Collapsible } from '../../components/collapsible/index.ts'

const SCOPE = 'chain-of-thought'

interface ChainOfThoughtContextValue {
  isOpen: boolean
  setIsOpen: (open: boolean) => void
}

let currentContext: ChainOfThoughtContextValue | undefined

export function useChainOfThought(): ChainOfThoughtContextValue {
  if (!currentContext) {
    throw new Error('ChainOfThought components must be used within ChainOfThought')
  }
  return currentContext
}

export type ChainOfThoughtProps = JSX.HTMLAttributes<HTMLDivElement> & {
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
  open?: boolean
}

export function ChainOfThought(props: ChainOfThoughtProps) {
  const [local, rest] = splitProps(props, ['defaultOpen', 'onOpenChange', 'open'])
  const [isOpen, setIsOpenRaw] = createSignal(local.open ?? local.defaultOpen ?? false)
  const setIsOpen = (open: boolean) => {
    setIsOpenRaw(open)
    local.onOpenChange?.(open)
  }
  currentContext = {
    get isOpen() {
      return isOpen()
    },
    setIsOpen,
  }

  return (
    <div data-scope={SCOPE} data-part="root" {...rest}>
      {props.children}
    </div>
  )
}

export type ChainOfThoughtHeaderProps = JSX.HTMLAttributes<HTMLButtonElement> & {
  indicator?: JSX.Element
}

export function ChainOfThoughtHeader(props: ChainOfThoughtHeaderProps) {
  const [local, rest] = splitProps(props, ['children', 'indicator'])
  const { isOpen, setIsOpen } = useChainOfThought()

  return (
    <Collapsible.Root onOpenChange={(details) => setIsOpen(details.open)} open={isOpen}>
      <Collapsible.Trigger data-scope={SCOPE} data-part="trigger" {...rest}>
        {local.children ?? 'Chain of Thought'}
        {local.indicator}
      </Collapsible.Trigger>
    </Collapsible.Root>
  )
}

export type ChainOfThoughtStepProps = JSX.HTMLAttributes<HTMLDivElement> & {
  description?: string
  icon?: JSX.Element
  label: string
  status?: 'active' | 'complete' | 'pending'
}

export function ChainOfThoughtStep(props: ChainOfThoughtStepProps) {
  const [local, rest] = splitProps(props, ['description', 'icon', 'label', 'status', 'children'])
  const status = () => local.status ?? 'complete'

  return (
    <div data-scope={SCOPE} data-part="step" data-status={status()} {...rest}>
      <div data-scope={SCOPE} data-part="step-marker">
        {local.icon}
      </div>
      <div data-scope={SCOPE} data-part="step-body">
        <div data-scope={SCOPE} data-part="step-label">
          {local.label}
        </div>
        <Show when={local.description}>
          <div data-scope={SCOPE} data-part="step-description">
            {local.description}
          </div>
        </Show>
        {local.children}
      </div>
    </div>
  )
}

export type ChainOfThoughtSearchResultsProps = JSX.HTMLAttributes<HTMLDivElement>

export function ChainOfThoughtSearchResults(props: ChainOfThoughtSearchResultsProps) {
  return <div data-scope={SCOPE} data-part="search-results" {...props} />
}

export type ChainOfThoughtSearchResultProps = JSX.HTMLAttributes<HTMLSpanElement>

export function ChainOfThoughtSearchResult(props: ChainOfThoughtSearchResultProps) {
  return <span data-scope={SCOPE} data-part="search-result" {...props} />
}

export type ChainOfThoughtContentProps = JSX.HTMLAttributes<HTMLDivElement>

export function ChainOfThoughtContent(props: ChainOfThoughtContentProps) {
  const { isOpen } = useChainOfThought()
  return (
    <Collapsible.Root open={isOpen}>
      <Collapsible.Content data-scope={SCOPE} data-part="content" {...props} />
    </Collapsible.Root>
  )
}

export type ChainOfThoughtImageProps = JSX.HTMLAttributes<HTMLDivElement> & {
  caption?: string
}

export function ChainOfThoughtImage(props: ChainOfThoughtImageProps) {
  const [local, rest] = splitProps(props, ['caption', 'children'])
  return (
    <div data-scope={SCOPE} data-part="image" {...rest}>
      <div data-scope={SCOPE} data-part="image-frame">
        {local.children}
      </div>
      <Show when={local.caption}>
        <p data-scope={SCOPE} data-part="image-caption">
          {local.caption}
        </p>
      </Show>
    </div>
  )
}
