// packages/solid/src/ai/sandbox/sandbox.tsx
import { Show, splitProps } from 'solid-js'
import type { JSX } from 'solid-js'
import { CollapsibleRoot, CollapsibleTrigger, CollapsibleContent } from '../../components/collapsible/index.ts'
import { TabsRoot, TabList, TabTrigger, TabContent } from '../../components/tabs/index.ts'

const SCOPE = 'sandbox'

export type SandboxProps = JSX.HTMLAttributes<HTMLDivElement> & {
  defaultOpen?: boolean
}

export function Sandbox(props: SandboxProps) {
  const [local, rest] = splitProps(props, ['defaultOpen'])
  return (
    <CollapsibleRoot defaultOpen={local.defaultOpen ?? true} data-scope={SCOPE} data-part="root" {...(rest as any)} />
  )
}

export type SandboxHeaderProps = JSX.HTMLAttributes<HTMLButtonElement> & {
  indicator?: JSX.Element
  state?: 'input-streaming' | 'input-available' | 'output-available' | 'output-error'
  title?: JSX.Element
}

export function SandboxHeader(props: SandboxHeaderProps) {
  const [local, rest] = splitProps(props, ['indicator', 'state', 'title', 'children'])
  const statusText = () =>
    local.state === 'output-error' ? 'Error' : local.state === 'output-available' ? 'Done' : 'Running'

  const content = () =>
    local.children ?? (
      <span data-scope={SCOPE} data-part="header-identity">
        <span data-scope={SCOPE} data-part="title">
          {local.title}
        </span>
        <Show when={local.state}>
          <span data-scope={SCOPE} data-part="status" data-state={local.state}>
            {statusText()}
          </span>
        </Show>
        {local.indicator}
      </span>
    )

  return (
    <CollapsibleTrigger data-scope={SCOPE} data-part="header" {...(rest as any)}>
      {content() as any}
    </CollapsibleTrigger>
  )
}

export type SandboxContentProps = JSX.HTMLAttributes<HTMLDivElement>

export function SandboxContent(props: SandboxContentProps) {
  return <CollapsibleContent data-scope={SCOPE} data-part="content" {...(props as any)} />
}

export type SandboxTabsProps = Record<string, unknown>

export function SandboxTabs(props: SandboxTabsProps) {
  return <TabsRoot data-scope={SCOPE} data-part="tabs" {...(props as any)} />
}

export type SandboxTabsBarProps = JSX.HTMLAttributes<HTMLDivElement>

export function SandboxTabsBar(props: SandboxTabsBarProps) {
  return <div data-scope={SCOPE} data-part="tabs-bar" {...props} />
}

export type SandboxTabListProps = Record<string, unknown>

export function SandboxTabList(props: SandboxTabListProps) {
  return <TabList data-scope={SCOPE} data-part="tabs-list" {...(props as any)} />
}

export type SandboxTabTriggerProps = Record<string, unknown>

export function SandboxTabTrigger(props: SandboxTabTriggerProps) {
  return <TabTrigger data-scope={SCOPE} data-part="tabs-trigger" {...(props as any)} />
}

export type SandboxTabContentProps = Record<string, unknown>

export function SandboxTabContent(props: SandboxTabContentProps) {
  return <TabContent data-scope={SCOPE} data-part="tab-content" {...(props as any)} />
}

// packages/react/src/ai/sandbox/sandbox.tsx
import type { ComponentProps, ReactNode } from 'react'
import { Collapsible } from '../../components/collapsible/index.ts'
import { Tabs } from '../../components/tabs/index.ts'

const SCOPE = 'sandbox'

export type SandboxProps = ComponentProps<typeof Collapsible.Root> & {
  defaultOpen?: boolean
}

export function Sandbox({ defaultOpen = true, ...props }: SandboxProps) {
  return <Collapsible.Root data-scope={SCOPE} data-part="root" defaultOpen={defaultOpen} {...props} />
}

export type SandboxHeaderProps = ComponentProps<typeof Collapsible.Trigger> & {
  indicator?: ReactNode
  state?: 'input-streaming' | 'input-available' | 'output-available' | 'output-error'
  title?: ReactNode
}

export function SandboxHeader({ indicator, state, title, children, ...props }: SandboxHeaderProps) {
  return (
    <Collapsible.Trigger data-scope={SCOPE} data-part="header" {...props}>
      {children ?? (
        <span data-scope={SCOPE} data-part="header-identity">
          <span data-scope={SCOPE} data-part="title">
            {title}
          </span>
          {state && (
            <span data-scope={SCOPE} data-part="status" data-state={state}>
              {state === 'output-error' ? 'Error' : state === 'output-available' ? 'Done' : 'Running'}
            </span>
          )}
          {indicator}
        </span>
      )}
    </Collapsible.Trigger>
  )
}

export type SandboxContentProps = ComponentProps<typeof Collapsible.Content>

export function SandboxContent(props: SandboxContentProps) {
  return <Collapsible.Content data-scope={SCOPE} data-part="content" {...props} />
}

export type SandboxTabsProps = ComponentProps<typeof Tabs.Root>

export function SandboxTabs(props: SandboxTabsProps) {
  return <Tabs.Root data-scope={SCOPE} data-part="tabs" {...props} />
}

export type SandboxTabsBarProps = ComponentProps<'div'>

export function SandboxTabsBar({ children, ...props }: SandboxTabsBarProps) {
  return (
    <div data-scope={SCOPE} data-part="tabs-bar" {...props}>
      {children}
    </div>
  )
}

export type SandboxTabsListProps = ComponentProps<typeof Tabs.List>

export function SandboxTabsList(props: SandboxTabsListProps) {
  return <Tabs.List data-scope={SCOPE} data-part="tabs-list" {...props} />
}

export type SandboxTabsTriggerProps = ComponentProps<typeof Tabs.Trigger>

export function SandboxTabsTrigger(props: SandboxTabsTriggerProps) {
  return <Tabs.Trigger data-scope={SCOPE} data-part="tabs-trigger" {...props} />
}

export type SandboxTabContentProps = ComponentProps<typeof Tabs.Content>

export function SandboxTabContent(props: SandboxTabContentProps) {
  return <Tabs.Content data-scope={SCOPE} data-part="tab-content" {...props} />
}
