// packages/vue/src/components/progress/progress-circle.vue
<script lang="ts">
import type { SVGAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface ProgressCircleBaseProps extends PolymorphicProps {}
export interface ProgressCircleProps
  extends
    ProgressCircleBaseProps,
    /**
     * @vue-ignore
     */
    SVGAttributes {}
</script>

<script setup lang="ts">
import { codesign } from '../factory.ts'
import { useProgressContext } from './use-progress-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

defineProps<ProgressCircleProps>()
const progress = useProgressContext()

useForwardExpose()
</script>

<template>
  <codesign.svg v-bind="progress.getCircleProps()" :as-child="asChild">
    <slot />
  </codesign.svg>
</template>

// packages/solid/src/components/progress/progress-circle.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useProgressContext } from './use-progress-context.ts'

export interface ProgressCircleBaseProps extends PolymorphicProps<'svg'> {}
export interface ProgressCircleProps extends HTMLProps<'svg'>, ProgressCircleBaseProps {}

export const ProgressCircle = (props: ProgressCircleProps) => {
  const api = useProgressContext()
  const mergedProps = mergeProps(() => api().getCircleProps(), props)

  return <codesign.svg {...mergedProps} />
}
