// packages/react/src/components/tabs/tab-list.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useTabsContext } from './use-tabs-context.ts'

export interface TabListBaseProps extends PolymorphicProps {}
export interface TabListProps extends HTMLProps<'div'>, TabListBaseProps {}

export const TabList = forwardRef<HTMLDivElement, TabListProps>((props, ref) => {
  const tabs = useTabsContext()
  const mergedProps = mergeProps(tabs.getListProps(), props)

  return <codesign.div {...mergedProps} ref={ref} />
})

TabList.displayName = 'TabList'

// packages/vue/src/components/tabs/tab-list.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface TabListBaseProps extends PolymorphicProps {}
export interface TabListProps
  extends
    TabListBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { codesign } from '../factory.ts'
import { useTabsContext } from './use-tabs-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

defineProps<TabListProps>()
const tabs = useTabsContext()

useForwardExpose()
</script>

<template>
  <codesign.div v-bind="tabs.getListProps()" :as-child="asChild">
    <slot />
  </codesign.div>
</template>
