// packages/react/src/components/listbox/listbox-content.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useListboxContext } from './use-listbox-context.ts'

export interface ListboxContentBaseProps extends PolymorphicProps {}
export interface ListboxContentProps extends HTMLProps<'div'>, ListboxContentBaseProps {}

export const ListboxContent = forwardRef<HTMLDivElement, ListboxContentProps>((props, ref) => {
  const listbox = useListboxContext()
  const mergedProps = mergeProps(listbox.getContentProps(), props)

  return <codesign.div {...mergedProps} ref={ref} />
})

ListboxContent.displayName = 'ListboxContent'

// packages/svelte/src/lib/components/listbox/listbox-content.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types.js'

  export interface ListboxContentBaseProps extends PolymorphicProps<'div'>, RefAttribute {}
  export interface ListboxContentProps extends Assign<HTMLProps<'div'>, ListboxContentBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.js'
  import { useListboxContext } from './use-listbox-context.js'

  let { ref = $bindable(null), ...props }: ListboxContentProps = $props()

  const listbox = useListboxContext()
  const mergedProps = $derived(mergeProps(listbox().getContentProps(), props))
</script>

<Codesign as="div" bind:ref {...mergedProps} />
