// packages/react/src/components/listbox/listbox-label.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useListboxContext } from './use-listbox-context.ts'

export interface ListboxLabelBaseProps extends PolymorphicProps {}
export interface ListboxLabelProps extends HTMLProps<'span'>, ListboxLabelBaseProps {}

export const ListboxLabel = forwardRef<HTMLSpanElement, ListboxLabelProps>((props, ref) => {
  const listbox = useListboxContext()
  const mergedProps = mergeProps(listbox.getLabelProps(), props)

  return <codesign.span {...mergedProps} ref={ref} />
})

ListboxLabel.displayName = 'ListboxLabel'

// packages/svelte/src/lib/components/listbox/listbox-label.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types.js'

  export interface ListboxLabelBaseProps extends PolymorphicProps<'span'>, RefAttribute {}
  export interface ListboxLabelProps extends Assign<HTMLProps<'span'>, ListboxLabelBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.js'
  import { useListboxContext } from './use-listbox-context.js'

  let { ref = $bindable(null), ...props }: ListboxLabelProps = $props()

  const listbox = useListboxContext()
  const mergedProps = $derived(mergeProps(listbox().getLabelProps(), props))
</script>

<Codesign as="span" bind:ref {...mergedProps} />
