// packages/solid/src/components/steps/steps-trigger.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useStepsContext } from './use-steps-context.ts'
import { useStepsItemPropsContext } from './use-steps-item-props-context.ts'

export interface StepsTriggerBaseProps extends PolymorphicProps<'button'> {}
export interface StepsTriggerProps extends HTMLProps<'button'>, StepsTriggerBaseProps {}

export const StepsTrigger = (props: StepsTriggerProps) => {
  const steps = useStepsContext()
  const itemProps = useStepsItemPropsContext()
  const mergedProps = mergeProps(() => steps().getTriggerProps(itemProps), props)

  return <codesign.button {...mergedProps} />
}

// packages/svelte/src/lib/components/steps/steps-trigger.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface StepsTriggerBaseProps extends PolymorphicProps<'button'>, RefAttribute {}
  export interface StepsTriggerProps extends Assign<HTMLProps<'button'>, StepsTriggerBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useStepsContext } from './use-steps-context.ts'
  import { useStepsItemPropsContext } from './use-steps-item-props-context.ts'

  let { ref = $bindable(null), ...props }: StepsTriggerProps = $props()

  const steps = useStepsContext()
  const itemProps = useStepsItemPropsContext()
  const mergedProps = $derived(mergeProps(steps().getTriggerProps(itemProps()), props))
</script>

<Codesign as="button" bind:ref {...mergedProps} />
