// packages/solid/src/ai/tool/tool.tsx
import { Show, splitProps } from 'solid-js'
import type { JSX } from 'solid-js'
import { Collapsible } from '../../components/collapsible/index.ts'

export type ToolState =
  | 'approval-requested'
  | 'approval-responded'
  | 'input-available'
  | 'input-streaming'
  | 'output-available'
  | 'output-denied'
  | 'output-error'

const statusLabels: Record<ToolState, string> = {
  'approval-requested': 'Awaiting Approval',
  'approval-responded': 'Responded',
  'input-available': 'Running',
  'input-streaming': 'Pending',
  'output-available': 'Completed',
  'output-denied': 'Denied',
  'output-error': 'Error',
}

export function getStatusLabel(status: ToolState) {
  return statusLabels[status]
}

export type ToolProps = JSX.HTMLAttributes<HTMLDivElement>

export function Tool(props: ToolProps) {
  return <Collapsible.Root data-scope="tool" data-part="root" {...props} />
}

export type ToolHeaderProps = JSX.HTMLAttributes<HTMLButtonElement> & {
  state: ToolState
  title?: string
  toolName?: string
  type: string
}

export function ToolHeader(props: ToolHeaderProps) {
  const [local, rest] = splitProps(props, ['state', 'title', 'toolName', 'type'])
  const derivedName = local.type === 'dynamic-tool' ? (local.toolName ?? '') : local.type.split('-').slice(1).join('-')

  return (
    <Collapsible.Trigger data-scope="tool" data-part="trigger" {...rest}>
      <span data-scope="tool" data-part="title">
        {local.title ?? derivedName}
      </span>
      <span data-scope="tool" data-part="status" data-status={local.state}>
        {statusLabels[local.state]}
      </span>
    </Collapsible.Trigger>
  )
}

export type ToolContentProps = JSX.HTMLAttributes<HTMLDivElement>

export function ToolContent(props: ToolContentProps) {
  return <Collapsible.Content data-scope="tool" data-part="content" {...props} />
}

export type ToolInputProps = JSX.HTMLAttributes<HTMLDivElement> & {
  input: unknown
}

export function ToolInput(props: ToolInputProps) {
  const [local, rest] = splitProps(props, ['input'])
  return (
    <div data-scope="tool" data-part="input" {...rest}>
      <h4 data-scope="tool" data-part="label">
        Parameters
      </h4>
      <pre data-scope="tool" data-part="code">
        {JSON.stringify(local.input, null, 2)}
      </pre>
    </div>
  )
}

export type ToolOutputProps = JSX.HTMLAttributes<HTMLDivElement> & {
  errorText?: string
  output?: unknown
}

export function ToolOutput(props: ToolOutputProps) {
  const [local, rest] = splitProps(props, ['errorText', 'output'])

  return (
    <Show when={Boolean(local.output || local.errorText)} fallback={null}>
      <div data-scope="tool" data-part="output" data-error={local.errorText ? '' : undefined} {...rest}>
        <h4 data-scope="tool" data-part="label">
          {local.errorText ? 'Error' : 'Result'}
        </h4>
        <Show when={local.errorText}>
          <div data-scope="tool" data-part="error-text">
            {local.errorText}
          </div>
        </Show>
        <Show when={typeof local.output === 'string' || (typeof local.output === 'object' && local.output !== null)}>
          <pre data-scope="tool" data-part="code">
            {typeof local.output === 'string' ? local.output : JSON.stringify(local.output, null, 2)}
          </pre>
        </Show>
      </div>
    </Show>
  )
}

// packages/react/src/ai/tool/tool.tsx
import type { DynamicToolUIPart, ToolUIPart } from 'ai'
import type { ComponentProps, ReactNode } from 'react'
import { isValidElement } from 'react'
import { Collapsible } from '../../components/collapsible/index.ts'

export type ToolProps = ComponentProps<typeof Collapsible.Root>

export function Tool(props: ToolProps) {
  return <Collapsible.Root data-scope="tool" data-part="root" {...props} />
}

export type ToolPart = ToolUIPart | DynamicToolUIPart

export type ToolHeaderProps = Omit<ComponentProps<typeof Collapsible.Trigger>, 'onOpenChange' | 'type'> & {
  title?: string
  type: ToolPart['type']
  state: ToolPart['state']
  toolName?: string
}

const statusLabels: Record<ToolPart['state'], string> = {
  'approval-requested': 'Awaiting Approval',
  'approval-responded': 'Responded',
  'input-available': 'Running',
  'input-streaming': 'Pending',
  'output-available': 'Completed',
  'output-denied': 'Denied',
  'output-error': 'Error',
}

export function getStatusLabel(status: ToolPart['state']) {
  return statusLabels[status]
}

export function ToolHeader({ title, type, state, toolName, ...props }: ToolHeaderProps) {
  const derivedName = type === 'dynamic-tool' ? (toolName ?? '') : type.split('-').slice(1).join('-')

  return (
    <Collapsible.Trigger data-scope="tool" data-part="trigger" {...props}>
      <span data-scope="tool" data-part="title">
        {title ?? derivedName}
      </span>
      <span data-scope="tool" data-part="status" data-status={state}>
        {statusLabels[state]}
      </span>
    </Collapsible.Trigger>
  )
}

export type ToolContentProps = ComponentProps<typeof Collapsible.Content>

export function ToolContent(props: ToolContentProps) {
  return <Collapsible.Content data-scope="tool" data-part="content" {...props} />
}

export type ToolInputProps = ComponentProps<'div'> & {
  input: ToolPart['input']
}

export function ToolInput({ input, ...props }: ToolInputProps) {
  return (
    <div data-scope="tool" data-part="input" {...props}>
      <h4 data-part="label">Parameters</h4>
      <pre data-part="code">{JSON.stringify(input, null, 2)}</pre>
    </div>
  )
}

export type ToolOutputProps = ComponentProps<'div'> & {
  output?: ToolPart['output']
  errorText?: ToolPart['errorText']
}

export function ToolOutput({ output, errorText, ...props }: ToolOutputProps) {
  if (!(output || errorText)) {
    return null
  }

  let rendered: ReactNode = null
  if (typeof output === 'object' && output !== null && !isValidElement(output)) {
    rendered = <pre data-part="code">{JSON.stringify(output, null, 2)}</pre>
  } else if (typeof output === 'string') {
    rendered = <pre data-part="code">{output}</pre>
  } else if (output !== null && output !== undefined) {
    rendered = <div data-part="output-value">{output as ReactNode}</div>
  }

  return (
    <div data-scope="tool" data-part="output" data-error={errorText ? '' : undefined} {...props}>
      <h4 data-part="label">{errorText ? 'Error' : 'Result'}</h4>
      {errorText && <div data-part="error-text">{errorText}</div>}
      {rendered}
    </div>
  )
}
