// packages/svelte/src/lib/components/tour/tour-description.svelte
<script module lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface TourDescriptionBaseProps extends PolymorphicProps<'div'>, RefAttribute {}
  export interface TourDescriptionProps extends HTMLProps<'div'>, TourDescriptionBaseProps {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useTourContext } from './use-tour-context.ts'

  let { ref = $bindable(null), ...props }: TourDescriptionProps = $props()

  const tour = useTourContext()
  const mergedProps = $derived(mergeProps(tour().getDescriptionProps(), props))
</script>

<Codesign as="div" bind:ref {...mergedProps}>
  {#if props.children}
    {@render props.children()}
  {:else}
    {tour().step?.description}
  {/if}
</Codesign>

// packages/solid/src/components/tour/tour-description.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useTourContext } from './use-tour-context.ts'

export interface TourDescriptionBaseProps extends PolymorphicProps<'div'> {}
export interface TourDescriptionProps extends HTMLProps<'div'>, TourDescriptionBaseProps {}

export const TourDescription = (props: TourDescriptionProps) => {
  const tour = useTourContext()
  const mergedProps = mergeProps(() => tour().getDescriptionProps(), props)

  return <codesign.div {...mergedProps}>{mergedProps.children || tour().step?.description}</codesign.div>
}
