// packages/react/src/components/tour/tour-arrow.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useTourContext } from './use-tour-context.ts'

export interface TourArrowBaseProps extends PolymorphicProps {}
export interface TourArrowProps extends HTMLProps<'div'>, TourArrowBaseProps {}

export const TourArrow = forwardRef<HTMLDivElement, TourArrowProps>((props, ref) => {
  const tour = useTourContext()
  const mergedProps = mergeProps(tour.getArrowProps(), props)

  return tour.step?.arrow ? <codesign.div {...mergedProps} ref={ref} /> : null
})

TourArrow.displayName = 'TourArrow'

// packages/solid/src/components/tour/tour-arrow.tsx
import { mergeProps } from '@zag-js/solid'
import { Show } from 'solid-js'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useTourContext } from './use-tour-context.ts'

export interface TourArrowBaseProps extends PolymorphicProps<'div'> {}
export interface TourArrowProps extends HTMLProps<'div'>, TourArrowBaseProps {}

export const TourArrow = (props: TourArrowProps) => {
  const tour = useTourContext()
  const mergedProps = mergeProps(() => tour().getArrowProps(), props)

  return (
    <Show when={tour().step?.arrow}>
      <codesign.div {...mergedProps} />
    </Show>
  )
}
