// packages/svelte/src/lib/components/navigation-menu/navigation-menu-list.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface NavigationMenuListBaseProps extends PolymorphicProps<'div'>, RefAttribute {}
  export interface NavigationMenuListProps extends Assign<HTMLProps<'div'>, NavigationMenuListBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useNavigationMenuContext } from './use-navigation-menu-context.ts'

  let { ref = $bindable(null), ...props }: NavigationMenuListProps = $props()

  const navigationMenu = useNavigationMenuContext()
  const mergedProps = $derived(mergeProps(navigationMenu().getListProps(), props))
</script>

<Codesign as="div" bind:ref {...mergedProps} />

// packages/react/src/components/navigation-menu/navigation-menu-list.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useNavigationMenuContext } from './use-navigation-menu-context.ts'

export interface NavigationMenuListBaseProps extends PolymorphicProps {}
export interface NavigationMenuListProps extends HTMLProps<'div'>, NavigationMenuListBaseProps {}

export const NavigationMenuList = forwardRef<HTMLDivElement, NavigationMenuListProps>((props, ref) => {
  const navigationMenu = useNavigationMenuContext()
  const mergedProps = mergeProps(navigationMenu.getListProps(), props)

  return <codesign.div {...mergedProps} ref={ref} />
})

NavigationMenuList.displayName = 'NavigationMenuList'
