// packages/react/src/components/scroll-area/scroll-area-content.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useScrollAreaContext } from './use-scroll-area-context.ts'

export interface ScrollAreaContentBaseProps extends PolymorphicProps {}
export interface ScrollAreaContentProps extends HTMLProps<'div'>, ScrollAreaContentBaseProps {}

export const ScrollAreaContent = forwardRef<HTMLDivElement, ScrollAreaContentProps>((props, ref) => {
  const scrollArea = useScrollAreaContext()
  const mergedProps = mergeProps(scrollArea.getContentProps(), props)

  return <codesign.div {...mergedProps} ref={ref} />
})

ScrollAreaContent.displayName = 'ScrollAreaContent'

// packages/svelte/src/lib/components/scroll-area/scroll-area-content.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types.js'

  export interface ScrollAreaContentBaseProps extends PolymorphicProps<'div'>, RefAttribute {}
  export interface ScrollAreaContentProps extends Assign<HTMLProps<'div'>, ScrollAreaContentBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.js'
  import { useScrollAreaContext } from './use-scroll-area-context.js'

  let { ref = $bindable(null), ...props }: ScrollAreaContentProps = $props()

  const scrollArea = useScrollAreaContext()
  const mergedProps = $derived(mergeProps(scrollArea().getContentProps(), props))
</script>

<Codesign as="div" bind:ref {...mergedProps} />
