// packages/svelte/src/lib/components/toast/toast-title.svelte
<script lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types.js'
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.js'
  import { useToastContext } from './use-toast-context.js'

  export interface ToastTitleBaseProps extends PolymorphicProps<'div'>, RefAttribute {}

  export interface ToastTitleProps extends Assign<HTMLProps<'div'>, ToastTitleBaseProps> {}

  let { ref = $bindable(null), ...props }: ToastTitleProps = $props()

  const toast = useToastContext()
  const mergedProps = $derived(mergeProps(toast().getTitleProps(), props))
</script>

<Codesign as="div" bind:ref {...mergedProps} />

// packages/react/src/components/toast/toast-title.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useToastContext } from './use-toast-context.ts'

export interface ToastTitleBaseProps extends PolymorphicProps {}
export interface ToastTitleProps extends HTMLProps<'div'>, ToastTitleBaseProps {}

export const ToastTitle = forwardRef<HTMLDivElement, ToastTitleProps>((props, ref) => {
  const toast = useToastContext()
  const mergedProps = mergeProps(toast.getTitleProps(), props)

  return <codesign.div {...mergedProps} ref={ref} />
})

ToastTitle.displayName = 'ToastTitle'
