// packages/solid/src/components/carousel/carousel-progress-text.tsx
import { createMemo } from 'solid-js'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { carouselAnatomy } from './carousel.anatomy.ts'
import { useCarouselContext } from './use-carousel-context.ts'

const parts = carouselAnatomy.build()

export interface CarouselProgressTextBaseProps extends PolymorphicProps<'span'> {}
export interface CarouselProgressTextProps extends HTMLProps<'span'>, CarouselProgressTextBaseProps {}

export const CarouselProgressText = (props: CarouselProgressTextProps) => {
  const api = useCarouselContext()

  const progressText = createMemo(() => {
    const currentPage = api().page + 1
    const totalPages = api().pageSnapPoints.length
    return `${currentPage} / ${totalPages}`
  })

  return (
    <codesign.span {...parts.progressText.attrs} {...props}>
      {props.children || progressText()}
    </codesign.span>
  )
}

// packages/vue/src/components/carousel/carousel-progress-text.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface CarouselProgressTextBaseProps extends PolymorphicProps {}
export interface CarouselProgressTextProps
  extends
    CarouselProgressTextBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { codesign } from '../factory.ts'
import { carouselAnatomy } from './carousel.anatomy.ts'
import { useCarouselContext } from './use-carousel-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

const parts = carouselAnatomy.build()

defineProps<CarouselProgressTextProps>()
const carousel = useCarouselContext()

const progressText = computed(() => {
  const currentPage = carousel.value.page + 1
  const totalPages = carousel.value.pageSnapPoints.length
  return `${currentPage} / ${totalPages}`
})

useForwardExpose()
</script>

<template>
  <codesign.span v-bind="parts.progressText.attrs" :as-child="asChild">
    <slot>{{ progressText }}</slot>
  </codesign.span>
</template>
