// packages/svelte/src/lib/components/dialog/dialog-description.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface DialogDescriptionBaseProps extends PolymorphicProps<'div'>, RefAttribute {}
  export interface DialogDescriptionProps extends Assign<HTMLProps<'div'>, DialogDescriptionBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { useDialogContext } from './use-dialog-context.ts'

  let { ref = $bindable(null), ...props }: DialogDescriptionProps = $props()

  const dialog = useDialogContext()
  const mergedProps = $derived(mergeProps(dialog().getDescriptionProps(), props))
</script>

<Codesign as="div" bind:ref {...mergedProps} />

// packages/react/src/components/dialog/dialog-description.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { useDialogContext } from './use-dialog-context.ts'

export interface DialogDescriptionBaseProps extends PolymorphicProps {}
export interface DialogDescriptionProps extends HTMLProps<'div'>, DialogDescriptionBaseProps {}

export const DialogDescription = forwardRef<HTMLDivElement, DialogDescriptionProps>((props, ref) => {
  const dialog = useDialogContext()
  const mergedProps = mergeProps(dialog.getDescriptionProps(), props)

  return <codesign.div {...mergedProps} ref={ref} />
})

DialogDescription.displayName = 'DialogDescription'
