// packages/solid/src/components/rating-group/rating-group-hidden-input.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useFieldContext } from '../field/index.tsx'
import { useRatingGroupContext } from './use-rating-group-context.ts'

export interface RatingGroupHiddenInputBaseProps extends PolymorphicProps<'input'> {}
export interface RatingGroupHiddenInputProps extends HTMLProps<'input'>, RatingGroupHiddenInputBaseProps {}

export const RatingGroupHiddenInput = (props: RatingGroupHiddenInputProps) => {
  const ratingGroup = useRatingGroupContext()
  const mergedProps = mergeProps(() => ratingGroup().getHiddenInputProps(), props)
  const field = useFieldContext()

  return <codesign.input aria-describedby={field?.().ariaDescribedby} {...mergedProps} />
}

// packages/vue/src/components/rating-group/rating-group-hidden-input.vue
<script lang="ts">
import type { InputHTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface RatingGroupHiddenInputBaseProps extends PolymorphicProps {}
export interface RatingGroupHiddenInputProps
  extends
    RatingGroupHiddenInputBaseProps,
    /**
     * @vue-ignore
     */
    InputHTMLAttributes {}
</script>

<script setup lang="ts">
import { codesign } from '../factory.ts'
import { useRatingGroupContext } from './use-rating-group-context.ts'
import { useFieldContext } from '../field/index.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

defineProps<RatingGroupHiddenInputProps>()

const ratingGroup = useRatingGroupContext()
const field = useFieldContext()

useForwardExpose()
</script>

<template>
  <codesign.input
    :aria-describedby="field?.ariaDescribedby"
    v-bind="ratingGroup.getHiddenInputProps()"
    :as-child="asChild"
  >
    <slot />
  </codesign.input>
</template>
