// packages/solid/src/components/rating-group/rating-group-root-provider.tsx
import { mergeProps } from '@zag-js/solid'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import type { UseRatingGroupReturn } from './use-rating-group.ts'
import { RatingGroupProvider } from './use-rating-group-context.ts'

interface RootProviderProps {
  value: UseRatingGroupReturn
}

export interface RatingGroupRootProviderBaseProps extends PolymorphicProps<'div'> {}
export interface RatingGroupRootProviderProps
  extends HTMLProps<'div'>, RootProviderProps, RatingGroupRootProviderBaseProps {}

export const RatingGroupRootProvider = (props: RatingGroupRootProviderProps) => {
  const [{ value: ratingGroup }, localProps] = createSplitProps<RootProviderProps>()(props, ['value'])
  const mergedProps = mergeProps(() => ratingGroup().getRootProps(), localProps)

  return (
    <RatingGroupProvider value={ratingGroup}>
      <codesign.div {...mergedProps} />
    </RatingGroupProvider>
  )
}

// packages/vue/src/components/rating-group/rating-group-root-provider.vue
<script lang="ts">
import type { HTMLAttributes, UnwrapRef } from 'vue'
import type { PolymorphicProps } from '../factory.ts'
import type { UseRatingGroupReturn } from './use-rating-group.ts'

interface RootProviderProps {
  value: UnwrapRef<UseRatingGroupReturn>
}

export interface RatingGroupRootProviderBaseProps extends RootProviderProps, PolymorphicProps {}
export interface RatingGroupRootProviderProps
  extends
    RatingGroupRootProviderBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { codesign } from '../factory.ts'
import { RatingGroupProvider } from './use-rating-group-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

const props = defineProps<RatingGroupRootProviderProps>()
const ratingGroup = computed(() => props.value)

RatingGroupProvider(ratingGroup)

useForwardExpose()
</script>

<template>
  <codesign.div v-bind="ratingGroup.getRootProps()" :as-child="asChild">
    <slot />
  </codesign.div>
</template>
