// packages/react/src/components/toggle-group/toggle-group-root.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import type { Assign } from '../../types.ts'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.ts'
import { type UseToggleGroupProps, useToggleGroup } from './use-toggle-group.ts'
import { ToggleGroupProvider } from './use-toggle-group-context.ts'

export interface ToggleGroupRootBaseProps extends UseToggleGroupProps, PolymorphicProps {}
export interface ToggleGroupRootProps extends Assign<HTMLProps<'div'>, ToggleGroupRootBaseProps> {}

const splitRootProps = createSplitProps<UseToggleGroupProps>()

export const ToggleGroupRoot = forwardRef<HTMLDivElement, ToggleGroupRootProps>((props, ref) => {
  const [useToggleGroupProps, localProps] = splitRootProps(props, [
    'defaultValue',
    'deselectable',
    'disabled',
    'id',
    'ids',
    'loopFocus',
    'multiple',
    'onValueChange',
    'orientation',
    'rovingFocus',
    'value',
  ])
  const togglegroup = useToggleGroup(useToggleGroupProps)
  const mergedProps = mergeProps(togglegroup.getRootProps(), localProps)

  return (
    <ToggleGroupProvider value={togglegroup}>
      <codesign.div {...mergedProps} ref={ref} />
    </ToggleGroupProvider>
  )
})

ToggleGroupRoot.displayName = 'ToggleGroupRoot'

// packages/svelte/src/lib/components/toggle-group/toggle-group-root.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'
  import type { UseToggleGroupProps } from './use-toggle-group.svelte.ts'

  export interface ToggleGroupRootBaseProps extends UseToggleGroupProps, PolymorphicProps<'div'>, RefAttribute {}
  export interface ToggleGroupRootProps extends Assign<HTMLProps<'div'>, ToggleGroupRootBaseProps> {}
</script>

<script lang="ts">
  import { createSplitProps } from '$lib/utils/create-split-props'
  import { mergeProps } from '@zag-js/svelte'
  import { Codesign } from '../factory/index.ts'
  import { ToggleGroupProvider } from './use-toggle-group-context.ts'
  import { useToggleGroup } from './use-toggle-group.svelte.ts'

  let { ref = $bindable(null), value = $bindable<string[]>(), ...props }: ToggleGroupRootProps = $props()

  const [useToggleGroupProps, localProps] = $derived(
    createSplitProps<UseToggleGroupProps>()(props, [
      'defaultValue',
      'deselectable',
      'disabled',
      'id',
      'ids',
      'loopFocus',
      'multiple',
      'onValueChange',
      'orientation',
      'rovingFocus',
      'value',
    ]),
  )

  const id = $props.id()

  const machineProps = $derived.by<UseToggleGroupProps>(() => ({
    ...useToggleGroupProps,
    id: useToggleGroupProps.id ?? id,
    value,
    onValueChange(details) {
      useToggleGroupProps.onValueChange?.(details)
      if (value !== undefined) value = details.value
    },
  }))

  const toggleGroup = useToggleGroup(() => machineProps)
  const mergedProps = $derived(mergeProps(toggleGroup().getRootProps(), localProps))

  ToggleGroupProvider(toggleGroup)
</script>

<Codesign as="div" bind:ref {...mergedProps} />
