// packages/vue/src/components/switch/switch-label.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface SwitchLabelBaseProps extends PolymorphicProps {}
export interface SwitchLabelProps
  extends
    SwitchLabelBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { codesign } from '../factory.ts'
import { useSwitchContext } from './use-switch-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

defineProps<SwitchLabelProps>()
const context = useSwitchContext()

useForwardExpose()
</script>

<template>
  <codesign.span v-bind="context.getLabelProps()" :as-child="asChild">
    <slot />
  </codesign.span>
</template>

// packages/solid/src/components/switch/switch-label.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, codesign } from '../factory.tsx'
import { useSwitchContext } from './use-switch-context.ts'

export interface SwitchLabelBaseProps extends PolymorphicProps<'span'> {}
export interface SwitchLabelProps extends HTMLProps<'span'>, SwitchLabelBaseProps {}

export const SwitchLabel = (props: SwitchLabelProps) => {
  const api = useSwitchContext()
  const mergedProps = mergeProps(() => api().getLabelProps(), props)

  return <codesign.span {...mergedProps} />
}
